[tool.poetry]
name = "maglev"
version = "0.0.1.post2"
description = "Python utilities for working with NVIDIA's MLOps infrastructure."
readme = "README.md"
# NOTE: only the first item in authors/maintainers is listed in the PyPI
#       metadata.
authors = [
  "Eric Hall <ehall@nvidia.com>",
  "Ryan Miller <rjmill@nvidia.com>",
  "Ville Kallioniemi <vkallioniemi@nvidia.com>",
]
maintainers = [
  "Ryan Miller <rjmill@nvidia.com>",
  "Eric Hall <ehall@nvidia.com>",
  "Ville Kallioniemi <vkallioniemi@nvidia.com>",
]

license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
