[tool.poetry]
name = "lintersmagic"
version = "0.1.1"
description = "A package to include linters in Databricks notebooks: pycodestyle"
authors = ["Bedrock streaming"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"
pycodestyle = "2.8.0"
ipython = "7.17"

[tool.poetry.dev-dependencies]
unittest = "^0.0"
black = "^22.1.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
