
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T13:27:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f246470457f17483399eb10ef2706a4c434f0dd",
 "version": "0.0.70.post0.dev59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
