[tool.poetry]
name = "mtrampic-AWS-Utils"
version = "0.1.1"
description = "Mini CLI to help work with AWS in Cross-Account setup."
authors = ["Mladen Trampic <mladen@trampic.info>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.6.1"
pydantic = "^1.5.1"
typer-cli = "0.0.12"
boto3 = "^1.21.22"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
black = "^20.8b1"
isort = "^5.0.5"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pre-commit = "^2.4.0"
pytest = "^6.0.1"
pytest-cov = "^2.8.1"
mkdocs = "^1.1"
mkdocs-material = "^6.0.1"
markdown-include = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
aws-utils-cli = "mtrampic_aws_utils.main:app"