
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T14:44:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "33f35963bf115ce20a12a8c7a7c5b5cb0be008e6",
 "version": "0.0.70.post0.dev61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
