
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T00:34:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b64fa948acd59d2306be678f0f5f5071a2f338c",
 "version": "0.0.70.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
