
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T13:35:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a76291035dbc8bc36b2b8eb308f1bc21f9b94ca3",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
