[tool.poetry]
name = "ingeniictl"
version = "0.2.2"
description = "Ingenii's Swiss Army Knife"
authors = ["Teodor Kostadinov <teodor@ingenii.dev>"]
readme = "README.md"

[tool.poetry.scripts]
ingeniictl = "ingeniictl.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
