
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T15:23:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2868f511629bf0a1eb9c073bd952c4b20e7a20a",
 "version": "0.37.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
