import os

PROMETEO_PROVIDER = os.environ.get('PROMETEO_PROVIDER')
PROMETEO_USERNAME = os.environ.get('PROMETEO_USERNAME')
PROMETEO_PASSWORD = os.environ.get('PROMETEO_PASSWORD')

PROMETO_ENVIRONMENT = os.environ.get('PROMETEO_ENVIRONMENT')


