# Generated by Django 3.0.10 on 2021-02-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_line_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Order number'),
        ),
    ]
