# Generated by Django 3.2.11 on 2022-02-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_basket_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='order_number',
        ),
    ]
