[tool.poetry]
name = "amitkh_wordle"
version = "0.1.0"
description = "Entropy based Wordle Solver (CLI). Inspired by 3 Blue 1 Brown"
authors = ["Amit Kumar <amitkh@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/amit-kumarh/wordle-solver"

packages = [
    { include = "amitkh_wordle" }
]

[tool.poetry.scripts]
wordle = "amitkh_wordle.wordle:app"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
typer = "^0.4.0"
tqdm = "^4.63.0"
scipy = "^1.8.0"
wordfreq = "^3.0.0"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
