# Generated by Django 3.0.10 on 2020-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
