# Generated by Django 3.0.10 on 2020-12-11 16:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20201208_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Specialprice'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='specialprice_end',
            field=models.DateField(blank=True, null=True, verbose_name='Specialprice Enddate'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='specialprice_start',
            field=models.DateField(blank=True, null=True, verbose_name='Specialprice Startdate'),
        ),
    ]
