# Generated by Django 3.0.10 on 2020-12-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20201211_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='specialprice_end',
            new_name='special_price_end',
        ),
    ]
