# Generated by Django 3.0.10 on 2020-12-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20201211_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='special_price_end',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='special_price_start',
        ),
    ]
