# Generated by Django 3.0.10 on 2020-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20201212_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
