# Generated by Django 3.2.9 on 2021-12-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_zero_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'ordering': ('product_id', '-partner__priority'), 'verbose_name': 'Stock record', 'verbose_name_plural': 'Stock records'},
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together={('partner', 'partner_sku')},
        ),
    ]
