# Generated by Django 3.2.11 on 2022-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='wishlist_as_link',
            field=models.BooleanField(default=False, help_text='Favoriten werden im Filter als Link angezeigt', verbose_name='Favoriten als Links'),
        ),
    ]
