
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T12:42:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cadf5477d5d5b9905207ea236d87ccc26aeb72f8",
 "version": "1.99.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
