
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T14:21:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9b823faf755d21ae4377c08aa6a0d39a7bd1bb3",
 "version": "3.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
