
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T22:45:40+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "86c1ebf228869ef835933ae5d9bcaff48f0d3d59",
 "version": "v0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
