# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpel_products', '0002_alter_product_is_sellable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingService',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_products.product')),
                ('audience_criterias', models.TextField(verbose_name='Audience criterias')),
            ],
            options={
                'verbose_name': 'Training and Coaching',
                'verbose_name_plural': 'Training and Coachings',
                'db_table': 'simpel_training_service',
                'permissions': (('export_trainingservice', 'Can export Training Service'), ('import_trainingservice', 'Can import Training Service')),
            },
            bases=('simpel_products.product',),
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mod_training.trainingservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Training Topic',
                'verbose_name_plural': 'Training Topics',
                'db_table': 'simpel_product_training_topic',
                'permissions': (('export_trainingtopic', 'Can export Training Topic'), ('import_trainingtopic', 'Can import Training Topic')),
            },
        ),
    ]
