# Generated by Django 3.0.10 on 2020-12-02 10:57

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='Bank account', max_length=128, verbose_name='Card Type')),
                ('owner', models.CharField(max_length=150, verbose_name='Account owner')),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('bic', localflavor.generic.models.BICField(max_length=11, verbose_name='BIC')),
            ],
        ),
    ]
