# Generated by Django 3.0.10 on 2020-12-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_bankaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bic',
        ),
    ]
