# Generated by Django 3.0.10 on 2021-01-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_bankaccount_bic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
