# Generated by Django 3.1.6 on 2021-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_migrate_payment_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['-enabled', 'display_order'], 'verbose_name': 'Source Type', 'verbose_name_plural': 'Source Types'},
        ),
    ]
