# Generated by Django 3.0.10 on 2020-12-02 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(-2, '2nd basement'), (-1, '1st basement'), (0, 'Ground floor'), (1, '1st floor'), (2, '2nd floor')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
    ]
