# Generated by Django 3.0.10 on 2020-12-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_useraddress_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
    ]
