# Generated by Django 3.0.10 on 2021-01-04 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0008_useraddress_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='Bank account', max_length=128, verbose_name='Card Type')),
                ('owner', models.CharField(max_length=150, verbose_name='Account owner')),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
