# Generated by Django 3.0.10 on 2021-01-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0009_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='address.UserAddress', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
