# Generated by Django 3.0.10 on 2021-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_auto_20210104_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
