# Generated by Django 3.0.10 on 2021-01-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_bankaccount_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='address.BankAccount', verbose_name='User'),
        ),
    ]
