# Generated by Django 3.0.10 on 2021-01-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_auto_20210105_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
    ]
