# Generated by Django 3.0.10 on 2021-01-14 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0015_auto_20210107_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(2, '2nd floor'), (1, '1st floor'), (0, 'Erdgeschoss / Aufzug vorhanden'), (-1, '1st basement'), (-2, '2nd basement')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=64, verbose_name='Title'),
        ),
    ]
