# Generated by Django 3.0.10 on 2021-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_auto_20210114_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
    ]
