# Generated by Django 3.0.10 on 2021-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_auto_20210202_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='sage_id',
            field=models.PositiveIntegerField(blank=True, help_text='Überschreibe Sage Kunden ID im Shop (ohne D am Anfang eingeben)', null=True, verbose_name='Überschreibe Sage ID'),
        ),
    ]
