# Generated by Django 3.0.10 on 2021-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_useraddress_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='cost_center',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostenstelle'),
        ),
    ]
