# Generated by Django 3.1.6 on 2021-02-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_useraddress_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='cost_center',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostenstelle / Ihre Referenz'),
        ),
    ]
