# Generated by Django 3.1.6 on 2021-02-24 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0021_auto_20210216_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postcode',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(10000, 'Eine Postleitzahl muss größer sein'), django.core.validators.MaxValueValidator(99999, 'Eine Postleitzahl muss kleiner sein')], verbose_name='Post/Zip-code'),
        ),
    ]
