# Generated by Django 3.1.6 on 2021-06-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_migrate_payment_data'),
        ('address', '0023_auto_20210425_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankaccounts', to='payment.bankcard', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choose Floor'),
        ),
    ]
