# Generated by Django 3.1.6 on 2021-06-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0024_auto_20210605_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'managed': False},
        ),
    ]
