
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-25T11:37:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e309b67cbbeacc0d81cfc5b38a86e985378cf817",
 "version": "0.7.1.post.dev463"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
