# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b2ba580
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: gradedoc
include_funding: true
project_email: blake.naccarato+gradedoc@gmail.com
project_name: gradedoc
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
year_of_project_creation: 2022
