
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T11:04:54+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "23597d6ed37c48f83a2cff8ddd62cdf22de71b55",
 "version": "0.26.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
