# Generated by Django 3.0.10 on 2020-12-12 12:18

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_conditionaloffer_combinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='value',
            field=oscar.models.fields.PositiveDecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Value'),
        ),
    ]
