# Generated by Django 3.0.10 on 2020-12-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20201212_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsWithSpecialPriceRange',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.range',),
        ),
    ]
