# Generated by Django 3.0.10 on 2020-12-13 12:37

from django.db import migrations
from oscar.apps.offer.custom import create_range, create_benefit
from apps.offer.benefits import SpecialPriceBenefit








class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_productswithspecialpricerange'),
    ]

    operations = []
