# Generated by Django 3.0.10 on 2020-12-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_create_ranges_and_benefit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsWithSpecialPriceRange',
        ),
        migrations.CreateModel(
            name='SpecialPriceBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.fixedpricebenefit',),
        ),
    ]
