# Generated by Django 3.1.6 on 2021-05-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_product_priority'),
        ('offer', '0016_auto_20210518_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
    ]
