# Generated by Django 3.1.6 on 2021-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_auto_20210519_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeproduct',
            name='special_price_end',
            field=models.DateTimeField(blank=True, help_text='Enddatum dieses Produkt-Angebots.', null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='special_price_start',
            field=models.DateTimeField(blank=True, help_text='Startdatum dieses Produkt-Angebots.', null=True, verbose_name='Start date'),
        ),
    ]
