# Generated by Django 3.1.6 on 2021-05-19 18:26

from django.db import migrations
from django.db.models import Q
from django.utils import timezone






class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_auto_20210519_1930'),
    ]

    operations = []
