# Generated by Django 3.1.6 on 2021-05-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_migrate_special_prices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialPriceBenefit',
        ),
        migrations.RemoveField(
            model_name='conditionaloffer',
            name='range',
        ),
    ]
