# Generated by Django 3.1.6 on 2021-05-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20210519_2104'),
        ('offer', '0021_auto_20210521_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSpecialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Angebotspreis')),
                ('active_start', models.DateTimeField(blank=True, help_text='Startdatum dieses Produkt-Angebots.', null=True, verbose_name='Start date')),
                ('active_end', models.DateTimeField(blank=True, help_text='Startdatum dieses Produkt-Angebots.', null=True, verbose_name='End date')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_special_prices', to='offer.benefit')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_special_prices', to='offer.conditionaloffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_special_prices', to='catalogue.product')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_special_prices', to='offer.range')),
                ('range_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_special_prices', to='offer.rangeproduct')),
            ],
            options={
                'unique_together': {('product',)},
            },
        ),
    ]
