# Generated by Django 3.1.6 on 2021-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_activespecialprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeproduct',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ActiveSpecialPrice',
        ),
    ]
