# Generated by Django 3.1.6 on 2021-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0023_auto_20210529_2313'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rangeproduct',
            constraint=models.UniqueConstraint(fields=('range', 'product'), name='unique_range_product'),
        ),
    ]
