# Generated by Django 3.2.11 on 2022-02-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0026_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangeproduct',
            name='price_position',
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='main_title',
            field=models.CharField(default='ANGEBOT', help_text='Wird über dem Preislabel angezeigt, wenn nicht leer', max_length=20, verbose_name='Preisschild Überschrift'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Wird unter dem Preislabel angezeigt, wenn nicht leer', max_length=20, null=True, verbose_name='Preisschild Untertitel'),
        ),
        migrations.AlterField(
            model_name='rangeproduct',
            name='left',
            field=models.FloatField(blank=True, help_text='Vertikale Position des Preislabels', null=True, verbose_name='Vertikal %'),
        ),
        migrations.AlterField(
            model_name='rangeproduct',
            name='title',
            field=models.CharField(blank=True, help_text='Inhalt des Preislabels im Slide. Überschreibt den Titel des Produkts (wenn vorhanden).', max_length=100, null=True, verbose_name='Preisschild Label'),
        ),
        migrations.AlterField(
            model_name='rangeproduct',
            name='top',
            field=models.FloatField(blank=True, help_text='Horizontale Position des Preislabels', null=True, verbose_name='Horizontal %'),
        ),
        migrations.DeleteModel(
            name='SlidePriceLabelPosition',
        ),
    ]
