dictCapital={
        'State Name ': 'Capital ',
        'Andhra Pradesh': 'Amaravati',
        'Arunachal Pradesh': 'Itanagar',
        'Assam': 'Dispur',
        'Bihar ': 'Patna',
        'Chhattisgarh': 'Naya Raipur',
        'Goa': 'Panaji',
        'Gujarat': 'Gandhinagar',
        'Haryana': 'Chandigarh',
        'Himachal Pradesh': 'Shimla',
        'Jharkhand': 'Ranchi',
        'Karnataka': 'Bangalore',
        'Kerala': 'Thiruvananthapuram',
        'Madhya Pradesh': 'Bhopal',
        'Maharashtra': 'Mumbai ',
        'Manipur': 'Imphal',
        'Meghalaya': 'Shillong',
        'Mizoram': 'Aizawl',
        'Nagaland': 'Kohima',
        'Odisha': 'Bhubaneshwar',
        'Punjab': 'Chandigarh',
        'Rajasthan': 'Jaipur',
        'Sikkim': 'Gangtok',
        'Tamil Nadu': 'Chennai',
        'Telangana ': 'Hyderabad',
        'Tripura': 'Agartala',
        'Uttarakhand': 'Dehradun',
        'Uttar Pradesh ': 'Lucknow',
        'West Bengal': 'Kolkata'
    }
dictLanguage={
        'State Name ': 'Languages',
        'Andhra Pradesh': 'Telugu ',
        'Arunachal Pradesh': 'Monpa',
        'Assam': 'Assamese',
        'Bihar ': 'Hindi',
        'Chhattisgarh': 'Hindi',
        'Goa': 'Konkani',
        'Gujarat': 'Gujarati',
        'Haryana': 'Hindi',
        'Himachal Pradesh': 'Pahari',
        'Jharkhand': 'Hindi',
        'Karnataka': 'Kannada',
        'Kerala': 'Malayalam',
        'Madhya Pradesh': 'Hindi',
        'Maharashtra': 'Marathi',
        'Manipur': 'Manipuri',
        'Meghalaya': 'Khasi',
        'Mizoram': 'Mizo',
        'Nagaland': 'English',
        'Odisha': 'Oriya',
        'Punjab': 'Punjabi',
        'Rajasthan': 'Hindi',
        'Sikkim': 'Lepcha',
        'Tamil Nadu': 'Chennai',
        'Telangana ': 'Telugu',
        'Tripura': 'Bengali',
        'Uttarakhand': 'Hindi',
        'Uttar Pradesh ': 'Hindi',
        'West Bengal': 'Bengali'
    }
def getCapital(state):
    return(dictCapital[state])

def getLanguage(state):
    return(dictLanguage[state])
