#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['httpx_oauth', 'httpx_oauth.clients', 'httpx_oauth.integrations']

package_data = \
{'': ['*']}

install_requires = \
['httpx >=0.18,<0.23']

extras_require = \
{":python_version < '3.8'": ['typing-extensions']}

setup(name='httpx-oauth',
      version='0.5.0',
      description='Async OAuth client using HTTPX.',
      author='François Voron',
      author_email='fvoron@gmail.com',
      url='https://github.com/frankie567/httpx-oauth',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
