[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
[project]
dependencies = [
    "aioredis==2.0.1",
    "redis==4.1.4"
]
[project.optional-dependencies]
tests = [
    "mypy==0.931",
    "mypy-extensions==0.4.3",
    "typing_extensions==4.1.1"
]
