[tool.poetry]
name = "dynamo_api"
version = "0.1.0"
description = "Package to perform simple operations on AWS DynamoDB for personal use and playing around with Github Actions"
authors = ["Justin Lei <jun.lei@mail.mcgill.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.17.75"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
pytest-cov = "^2.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
