[tool.poetry]
name = "tsukuru"
version = "0.0.1"
description = "GUI Makefile creater"
authors = ["Yohei Osawa <yohei.osawa.318.niko8@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/senrust/tsukuru"
keywords = ["C", "Makefile", "GUI"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
