"""
    Nuaudit

    Nanaged Audit Trails for Cloud Applications.  # noqa: E501

    The version of the OpenAPI document: 0.19.0
    Contact: support@nuaudit.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nuaudit_python_autogen
from nuaudit_python_autogen.model.api_client_mutation import APIClientMutation


class TestAPIClientMutation(unittest.TestCase):
    """APIClientMutation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIClientMutation(self):
        """Test APIClientMutation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = APIClientMutation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
