"""
    Nuaudit

    Nanaged Audit Trails for Cloud Applications.  # noqa: E501

    The version of the OpenAPI document: 0.19.0
    Contact: support@nuaudit.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nuaudit_python_autogen
from nuaudit_python_autogen.model.actor import Actor
globals()['Actor'] = Actor
from nuaudit_python_autogen.model.actor_record import ActorRecord


class TestActorRecord(unittest.TestCase):
    """ActorRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActorRecord(self):
        """Test ActorRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActorRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
