[tool.poetry]
name = "dnevnik4python"
version = "0.0.8"
description = "Wrapper for python that simplifies work with dnevnik.ru"
readme = "README.md"
homepage = "https://github.com/hrog-zip/dnevnik4python"
keywords = ["python", "dnevnik", "dnevnikru", "api", "dnevnikru api", "dnevnik api", "wrapper"]
authors = ["hrog-zip <65674012+hrog-zip@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
lxml = "^4.8.0"
bs4 = "^0.0.1"
pytz = "^2022.1"
fake-useragent = "^0.1.11"

[tool.poetry.dev-dependencies]
mypy = "^0.941"
black = "^22.1.0"
flake8 = "^4.0.1"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
