[project]
name = "colassigner"
description = "Helper for assigning and accessing pandas columns"
authors = [
    "Endre Márk Borza"
]
license = "MIT"
readme = "README.md"
python = ">=3.7"
url = "https://github.com/endremborza/colassigner"
[build-system]
requires = [
    "toml >= 0.10.0",
    "setuptools >= 38.6.0, <61.0.0",
    "wheel >= 0.31.0",
    "setuptools_scm >= 2.0.0, <3"
]
[tool.bran]
line-length=79
