[tool.poetry]
name = "pyFaaS"
version = "0.3.1"
description = "Python client for Fluent as a Server"
authors = ["AlwinW <16846521+alwinw@users.noreply.github.com>"]
packages = [{ include = "faas" }]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
