
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T17:14:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "eaf9f98b7d9f56da02f4e17f8cd36894f1be2c3c",
 "version": "0.0.65.post0.dev374"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
