[tool.poetry]
name = "booting"
version = "1.0"
description = "1. Open install the module -> pip install booting 2. Write in your code this line -> from booting import keep_alive 3. and after this write keep_alive() 4. Done! Your discord bot repl is alive 24\\7."
authors = ["ENDER"]
license = "GNU-V3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
