
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T18:02:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f689bc75028b485e3527fe158a2940b5f69fc3b",
 "version": "0.0.70.post0.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
