[tool.poetry]
name = "dnevnik4python"
version = "0.0.6.1"
description = "Wrapper for python that simplifies work with dnevnik.ru"
authors = ["hrog-zip <65674012+hrog-zip@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/hrog-zip/dnevnik4python"
keywords = ["python", "dnevnik", "dnevnikru", "api", "dnevnikru api", "dnevnik api", "wrapper"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.27.1"
pytz = "^2022.1"
bs4 = "^0.0.1"
lxml = "^4.8.0"
fake-useragent = "^0.1.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
