
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T04:53:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f1e80d4ce56b62b6b474cea12744581472f9deb",
 "version": "1.16.0.post.dev300"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
