[tool.poetry]
name = "quickdump"
version = "0.3.0"
description = "Quickly store arbitrary Python objects in unique files."
keywords = ["quickdump", "dump", "serialize", "store"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pedrovhb/quickdump"
repository = "https://github.com/pedrovhb/quickdump"
authors = ["Pedro Batista <pedrovhb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
dill = "^0.3.4"
loguru = "^0.6.0"

starlette = {version = "^0.19.0", extras = ["server"]}
uvicorn = {version = "^0.17.6", extras = ["server"]}
pyzstd = "^0.15.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
mypy = "^0.941"
pylint = "^2.12.2"

[tool.poetry.scripts]
server = "quickdump.server:main"

# todo - cli interface, e.g. -
#  cat file | jq .key | qd -l some_label -s day


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
