# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpel_products', '0002_alter_product_is_sellable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionService',
            fields=[
                ('bundle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_products.bundle')),
            ],
            options={
                'verbose_name': 'Inspection Service',
                'verbose_name_plural': 'Inspection Services',
                'db_table': 'simpel_inspection_service',
                'permissions': (('export_inspectionservice', 'Can export Inspection Service'), ('import_inspectionservice', 'Can import Inspection Service')),
            },
            bases=('simpel_products.bundle',),
        ),
    ]
