# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpel_projects', '0001_initial'),
        ('mod_inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_projects.task')),
            ],
            options={
                'verbose_name': 'Inspection Task',
                'verbose_name_plural': 'Inspection Tasks',
                'db_table': 'simpel_inspection_task',
                'ordering': ('position',),
                'permissions': (('import_inspectiontask', 'Can import Inspection Task'), ('export_inspectiontask', 'Can export Inspection Task')),
            },
            bases=('simpel_projects.task',),
        ),
        migrations.CreateModel(
            name='InspectionTaskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('position', models.IntegerField(default=0, help_text='Enable sortable position', verbose_name='position')),
            ],
            options={
                'verbose_name': 'Inspection Task Parameter',
                'verbose_name_plural': 'Inspection Task Parameters',
                'db_table': 'simpel_inspection_task_parameter',
                'ordering': ('position',),
                'permissions': (('import_inspectiontaskparameter', 'Can import Inspection Task Parameter'), ('export_inspectiontaskparameter', 'Can export Inspection Task Parameter')),
            },
        ),
    ]
