[tool.poetry]
name = "iscc-schema"
version = "0.3.6"
description = "OpenAPI representation of the ISCC data model"
authors = ["Titusz <tp@py7.de>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iscc/iscc-schema"
keywords=["iscc", "identifier", "media", "content", "hash", "blockchain", "similarity"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0.0"
pydantic = "^1.9"
jcs = "^0.2"

[tool.poetry.dev-dependencies]
pytest = "*"
datamodel-code-generator = "^0.11"
poethepoet = "*"
black = { version = "21.12b0", allow-prereleases = true }
mkdocs-material = "*"
PyLD = "*"
requests = "^2.27.1"

[tool.black]
skip-string-normalization = false
line-length = 100
target-version = ['py37']


[tool.poe.tasks]
update = { cmd = "poetry update", help = "Update project dependencies"}
fromatyaml = { script = "tools.format_yaml:reformat", help = "Reformat yaml files"}
buildcode = { script = "tools.build_code:build", help = "Build code for API models"}
formatcode = { cmd = "black .", help = "Code style formating with black" }
buildterms = { script = "tools.build_terms:build", help = "Build markdown for terms" }
buildschema = { script = "tools.build_json_schema:build", help = "Generate JSON Schema" }
buildcontext = { script = "tools.build_json_ld_context:build", help = "Generate JSON-LD Context" }
builddocs = { script = "tools.build_docs:build", help = "Copy README.md to docs/index.md" }
test = { cmd = "pytest", help = "Run tests"}
all = ["fromatyaml", "buildcode", "formatcode", "buildterms", "buildschema", "buildcontext", "builddocs", "test"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
