
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-20T19:21:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "149e4ca25a8b7c14600a7080c49fd54268c49f18",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
