[tool.poetry]
name = "perfkits"
version = "0.0.1"
description = ""
authors = ["Gongziting Tech Ltd."]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
