
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T20:32:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0f6a5643e3ef878adaf086ed11fb26549b5b466",
 "version": "0.0.70.post0.dev47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
