
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T12:38:43+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d980409b394cd71cdd90f7afb2ce9c510303b2aa",
 "version": "1.0.8rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
