[project]
name = "hvl_ccb"
version = "0.8.4"
description = """
Python common code base to control devices high voltage research devices,
in particular, as used in the High Voltage Lab (HVL) of D-ITET, ETH
"""
readme = """
"""
requires-python = ">=3.7"
license = "GNU General Public License v3"
maintainers = [
    {name = "Henrik Menne", email = "menneh@ethz.ch"},
    {name = "Henning Janssen", email = "janssen@eeh.ee.ethz.ch"},
    {name = "Mikołaj Rybiński", email = "mikolaj.rybinski@id.ethz.ch"},
]
authors = [
    {name = "Mikołaj Rybiński", email = "mikolaj.rybinski@id.ethz.ch"},
    {name = "David Graber", email = "dev@davidgraber.ch"},
    {name = "Henrik Menne", email = "menneh@ethz.ch"},
    {name = "Alise Chachereau", email = "chachereau@eeh.ee.ethz.ch"},
    {name = "Henning Janssen", email = "janssen@eeh.ee.ethz.ch"},
    {name = "David Taylor", email = "dtaylor@ethz.ch"},
]
keywords = "hvl_ccb"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
    homepage = "https://pypi.org/project/hvl-ccb/"
    documentation = "https://readthedocs.org/projects/hvl-ccb/"
    repository = "https://gitlab.com/ethz_hvl/hvl_ccb/"
    changelog = "https://gitlab.com/ethz_hvl/hvl_ccb/-/blob/devel/HISTORY.rst"

[tool]