# Generated by Django 3.2.7 on 2022-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_pages', '0002_auto_20220319_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpelpage',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='simpelpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='simpelpage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
