# Generated by Django 3.2.7 on 2022-03-19 19:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_pages', '0003_auto_20220320_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpelpage',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='simpelpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
