name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Build wheel and source tarball
      id: build_tarball
      run: |
        python setup.py sdist
        version=$(head -1  cosmosis/version.py | cut  -d "'" -f 2)
        sha=$(shasum dist/cosmosis-${version}.tar.gz | awk '{print $1}')
        echo "::set-output name=tarball-sha::${sha}"
        echo "::set-output name=pypi-version::${version}"

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_COSMOSIS_UPLOAD }}

    - name: Make PR on cosmosis conda forge feedstock
      uses: joezuntz/cosmosis-action@v0.2
      with:
        token: ${{ secrets.PR_MAKER_TOKEN }}
        which-repository: cosmosis
        version: ${{ steps.build_tarball.outputs.pypi-version }}
        hash: ${{ steps.build_tarball.outputs.tarball-sha }}
