
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T12:53:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ac887589e6bccdbb89e0b290bc7abc99b1c4fd4",
 "version": "0.0.70.post0.dev57"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
