
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T15:58:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b78a8cb4d9fbaf3ac92d831943ef3b5d3c9a079",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
