[tool.poetry]
name = "HL7000"
version = "0.1.0"
description = "Processing toolkit for Seba HL7000"
authors = ["Cody Scott <jcodyscott@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^1.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
