[tool.poetry]
name = "metabase-manager"
version = "0.2.1"
description = "Manage your Metabase instance programmatically."
authors = ["Charles Lariviere"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/chasleslr/metabase-manager"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "metabase_manager", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "*"
metabase-python = "^0.3.0"
alive-progress = "*"

[tool.poetry.dev-dependencies]
black = "22.1.0"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
metabase-manager = 'metabase_manager.cli.main:cli'
