[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "awsswitch"
authors = [{name = "Tobias Sauerwein", email = "cgtobi@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

requires-python = ">=3.8"

dependencies = [
    "inquirerpy >=0.3.3",
]

[project.optional-dependencies]
test = [
    "pytest >=6.2.5",
    "pytest-cov",
]

[project.scripts]
awsswitch = "awsswitch:app"

[project.urls]
Home = "https://github.com/cgtobi/awsswitch"
