# Generated by Django 3.2.7 on 2022-02-28 18:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Company logo')),
                ('name', models.CharField(blank=True, help_text='Company name.', max_length=255, null=True, verbose_name='name')),
                ('address', models.TextField(blank=True, help_text='Complete address.', null=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, help_text='Public, valid email address.', max_length=50, null=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Valid phone with format +62XXXXXXX', max_length=128, null=True, region=None, verbose_name='phone')),
                ('website', models.CharField(blank=True, help_text='Your website url e.g  https://www.you.com', max_length=50, null=True, verbose_name='website')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
