# Generated by Django 3.2.7 on 2022-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_core', '0003_alter_generalsetting_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='tawkto_embed_url',
            field=models.URLField(blank=True, help_text='Your tawkto embed url e.g  https://embed.tawk.to/6154a63/1fgpampp1', null=True, verbose_name='TawkTo embedUrl'),
        ),
    ]
