# Generated by Django 3.2.7 on 2022-03-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('simpel_core', '0004_generalsetting_tawkto_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='website',
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='site_name',
            field=models.CharField(blank=True, help_text='Site name.', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Site Logo'),
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Site Logo')),
                ('name', models.CharField(blank=True, help_text='Company name.', max_length=255, null=True, verbose_name='name')),
                ('address', models.TextField(blank=True, help_text='Complete address.', null=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, help_text='Public, valid email address.', max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Valid phone with format +62XXXXXXX', max_length=15, null=True, verbose_name='phone')),
                ('website', models.CharField(blank=True, help_text='Your website url e.g  https://www.you.com', max_length=50, null=True, verbose_name='website')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
