[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pypergraph"
authors = [{name = "Xavier Lin"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.7"
dependencies = [
    "typing_extensions; python_version<'3.8'",
]
keywords = [
    "hypergraph",
    "datastructure",
]
version = "0.0.1"
description = "Hypergraph data structure in Python."

[project.urls]
# Displayed on PyPI listing
documentation = "https://pypergraph.readthedocs.io/"
source = "https://codeberg.org/meadow/pypergraph"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "flake8-docstrings",
    "flit",
    "isort",
    "mypy",
    "nox",
]

# Used by CI for linting
qa = [
    "flake8",
    "flake8-docstrings",
    "mypy",
]

# Used by CI for running unit tests
test = [
    "pytest",
    "pytest-cov",
]

# Used by Read the Docs when building documentation
# Used by CI for running doc tests (i.e. examples included into documentation)
doc = [
    "furo",
    "myst-parser",
    "sphinx",
]

[tool.black]
line-length = 80

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
line_length = 80
src_paths = [
    "src",
    "tests",
]