[tool.poetry]
name = "allrucodes"
version = "0.1.0"
description = "Python package with a collection of official all-russian codes catalogs."
authors = ["Alexey Naydyonov"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
fuzzywuzzy = "^0.18.0"

[tool.poetry.dev-dependencies]
black = "21.5b2"
isort = "^5.10.1"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
