[tool.poetry]
name = "goodhound"
version = "1.1.2"
description = "Attackers think in graphs, defenders think in actions, management think in charts.  GoodHound operationalises Bloodhound by determining the busiest paths to high value targets and creating actionable output to prioritise remediation of attack paths."
authors = ["Andi Morris <andi.morris@gmail.com>"]
license = "BSD-3-Clause"
homepage = "https://github.com/idnahacks/GoodHound"
repository = "https://github.com/idnahacks/GoodHound"
documentation = "https://github.com/idnahacks/GoodHound/wiki"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
py2neo = "=2021.2.3"
pandas = "=1.3.5"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
goodhound = 'goodhound:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
