# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-3x-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2022-03-22 19:32:48.366574
__version__ = '3.2.7'