[tool.poetry]
name = "nndict"
version = "2.0.0"
description = "A dict that does not support None entries. Silently deletes entry if updated to null and works recursively."
authors = ["Tiago Santos <tiago.santos@vizidox.com>"]
license = "MIT"
repository = "https://github.com/Morphotech/NeverNoneDict"
keywords = ["NeverNone", "Dict", "NeverNoneDict", "nndict"]
maintainers = ["Joana Teixeira <joana.teixeira@vizidox.com>",
               "Rita Mariquitos <rita.mariquitos@morphotech.co.uk>"]
classifiers = ["License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 3"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
tox = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
