
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-19T07:51:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d52afba324255061a5521ea071da6ee4d39d9e4",
 "version": "0.8.21b0.dev202203200713"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
