image: python:3.9
definitions:
  services:
    redis:
      image: redis
  steps:
    - step: &lint
        caches:
          - pip
        name: Lint
        script:
          - pip install pre-commit
          - pre-commit install
          - pre-commit run --all-files
    - step: &scan
        caches:
          - pip
        name: Scan
        script:
          - pip install .
          - pip install safety
          - safety check --full-report ${SAFETY_IGNORE}
    - step: &test
        caches:
          - pip
        name: Test
        script:
          - pip install .[test]
          - pytest -v -n auto -m "not development" --cov dkist_processing_common
        services:
          - redis
    - step: &push
        caches:
          - pip
        name: Push
        script:
          - python setup.py sdist
          - pip install twine
          - twine upload dist/*
    - step: &docs
        name: Test Docs
        caches:
          - pip
        script:
          - apt update && apt -y install graphviz
          - pip install .[docs]
          - sphinx-build --color -W --keep-going -b html docs docs/_build/html

pipelines:
  default:
    - step: *lint
    - step: *test
    - step: *docs
    - step: *scan
  tags:
    'v*':
      - step: *lint
      - step: *test
      - step: *docs
      - step: *scan
      - step: *push
