[tool.poetry]
name = "earthdata"
version = "0.2.2"
description = "Client library for NASA Earthdata APIs"
authors = ["Luis Lopez <betolin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6"
python-benedict = "^0.25"
python-cmr = "^0.4.1"
requests = "^2.26"
s3fs = ">=2021.11, <2023"
pqdm = "^0.1"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^21.11b0"
isort = "^5"
autoflake = "^1.3"
flake8 = "^3.7"
pre-commit = "^2.4"
pytest = "^6.0"
pytest-cov = "^2.8"
pytest-watch = "^4.2"
mkdocs = "^1.1"
mkdocs-material = "^6"
markdown-include = "^0.6"
responses = "^0.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
