# Generated by Django 3.2.7 on 2022-03-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_auth', '0002_auto_20220304_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
