
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T17:00:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "016d306c3ce7919eba3341cfb26e9509357b3301",
 "version": "0.0.19.post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
