# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_soup": "00_base.ipynb",
         "get_url": "01_event.ipynb",
         "get_event_name": "01_event.ipynb",
         "get_event_date": "01_event.ipynb",
         "generate_dict_from_table": "02_linescore.ipynb",
         "get_boxscore_from_table": "02_linescore.ipynb",
         "get_boxscore_from_game_id": "02_linescore.ipynb",
         "get_table_from_index": "02_linescore.ipynb",
         "get_boxscore_from_event_draw_game_number": "02_linescore.ipynb",
         "get_boxscore": "02_linescore.ipynb",
         "get_full_boxscore": "02_linescore.ipynb",
         "BOXSCORE_KWARGS": "03_constants.ipynb",
         "LINESCORE_SOUP_TYPE": "03_constants.ipynb",
         "BOXSCORE_SOUP_TYPE": "03_constants.ipynb"}

modules = ["core/scraping/base.py",
           "core/scraping/event.py",
           "core/scraping/linescore.py",
           "core/scraping/constants.py",
           "api.py"]

doc_url = "https://calicorob.github.io/czapi/"

git_url = "https://github.com/calicorob/czapi/tree/master/"

def custom_doc_links(name): return None
