[tool.poetry]
name = "nemesis"
version = "0.0.9"
description = "Tool for managing Elasticsearch resources as code"
authors = ["Nick Lang <nick@nicklang.com>"]
include = ["nemesis/templates/*.tmpl"]
readme = "README.md"
homepage = "https://github.com/fxdgear/nemesis"

[tool.poetry.dependencies]
python = "^3.6"
Click = "~7.1"
marshmallow = "^3.14.1"
dacite = "^1.6.0"
deepdiff = "^5.6.0"
elasticsearch = "^7.15.2"
python-dateutil = "^2.8.2"
rich = "^10.14.0"
requests = "^2.26.0"
pytz = "^2021.3"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "~21.7b0"
flake8 = "~3.9.2"
mypy = "~0.910"
pytest = "~6.2.4"
pytest-watch = "~4.2.0"
ipdb = "^0.13.9"
pytest-coverage = "^0.0"
mock = "^4.0.3"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.poetry.scripts]
nemesis = 'nemesis.scripts.nemesis:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
