# Generated by Django 2.2.27 on 2022-02-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0004_auto_20220215_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='djangoldp_circle.Circle'),
        ),
    ]
