# Generated by Django 2.2.27 on 2022-03-04 11:23

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0008_auto_20220303_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('product', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='djangoldp_sales.Product', verbose_name='produits')),
                ('removestock', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockorder', to='djangoldp_sales.Productstock', verbose_name='mouvement de stock')),
                ('sale', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleorder', to='djangoldp_sales.Sale', verbose_name='Vente')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
            },
        ),
    ]
