[tool.poetry]
name = "python-mealie-api"
version = "0.0.1-alpha.0"
description = "A python based mealie client"
authors = ["Marvin Straathof <marvinstraathof@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^7.1.1"
pyproject-flake8 = "^0.0.1a2"
pytest-cov = "^3.0.0"
pytest-aiohttp = "^1.0.4"
isort = "^5.10.1"
pytest-mock = "^3.7.0"
poetryup = "^0.5.4"
mypy = "^0.941"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=80
indent = "    "
force_sort_within_sections = true
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
default_section = "THIRDPARTY"
known_first_party = ["custom_components.mealie", "tests"]
combine_as_imports = true

[tool.flake8]
exclude = [
    ".venv",
    ".git",
    ".tox",
    "docs",
    "venv",
    "bin",
    "lib",
    "deps",
    "build"
]
max-line-length = 80
ignore = [
    "E501",
    "W503",
    "E203",
    "D202",
    "W504"
]

[tool.pytest]
addopts = "-qq --cov=python_mealie_api"
console_output_style = "count"
asyncio_mode="strict"

[tool.coverage.run]
branch = false

[tool.coverage.report]
show_missing = true
fail_under = 70

[[tool.mypy.overrides]]
module=["asynctest"]
ignore_missing_imports = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
