# Generated by Django 3.2.7 on 2022-03-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
