
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T19:24:40+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f97fb8f8f488a4f3201f61b29a1bc421a3c88ac2",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
