
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T07:23:12+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a83bb89e8de1b7118a52c35ecdfeaa322729fc0",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
