
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T17:32:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f50bbb37c5be843d2bd2952790d282758ab7b2a4",
 "version": "0.9.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
