# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/kafka_users/v1/kafka_users_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from strmprivacy.api.entities.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='strmprivacy/api/kafka_users/v1/kafka_users_v1.proto',
  package='strmprivacy.api.kafka_users.v1',
  syntax='proto3',
  serialized_options=b'\n!io.strmprivacy.api.kafka_users.v1P\001ZKgithub.com/strmprivacy/api-definitions-go/v2/api/kafka_users/v1;kafka_users',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3strmprivacy/api/kafka_users/v1/kafka_users_v1.proto\x12\x1estrmprivacy.api.kafka_users.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a-strmprivacy/api/entities/v1/entities_v1.proto\"X\n\x15ListKafkaUsersRequest\x12?\n\x03ref\x18\x01 \x01(\x0b\x32-.strmprivacy.api.entities.v1.KafkaExporterRefB\x03\xe0\x41\x02\"U\n\x16ListKafkaUsersResponse\x12;\n\x0bkafka_users\x18\x01 \x03(\x0b\x32&.strmprivacy.api.entities.v1.KafkaUser\"U\n\x16\x44\x65leteKafkaUserRequest\x12;\n\x03ref\x18\x01 \x01(\x0b\x32).strmprivacy.api.entities.v1.KafkaUserRefB\x03\xe0\x41\x02\"\x19\n\x17\x44\x65leteKafkaUserResponse\"T\n\x16\x43reateKafkaUserRequest\x12:\n\nkafka_user\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.KafkaUser\"U\n\x17\x43reateKafkaUserResponse\x12:\n\nkafka_user\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.KafkaUser\"R\n\x13GetKafkaUserRequest\x12;\n\x03ref\x18\x01 \x01(\x0b\x32).strmprivacy.api.entities.v1.KafkaUserRefB\x03\xe0\x41\x02\"R\n\x14GetKafkaUserResponse\x12:\n\nkafka_user\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.KafkaUser2\x99\x04\n\x11KafkaUsersService\x12\x7f\n\x0eListKafkaUsers\x12\x35.strmprivacy.api.kafka_users.v1.ListKafkaUsersRequest\x1a\x36.strmprivacy.api.kafka_users.v1.ListKafkaUsersResponse\x12y\n\x0cGetKafkaUser\x12\x33.strmprivacy.api.kafka_users.v1.GetKafkaUserRequest\x1a\x34.strmprivacy.api.kafka_users.v1.GetKafkaUserResponse\x12\x82\x01\n\x0f\x44\x65leteKafkaUser\x12\x36.strmprivacy.api.kafka_users.v1.DeleteKafkaUserRequest\x1a\x37.strmprivacy.api.kafka_users.v1.DeleteKafkaUserResponse\x12\x82\x01\n\x0f\x43reateKafkaUser\x12\x36.strmprivacy.api.kafka_users.v1.CreateKafkaUserRequest\x1a\x37.strmprivacy.api.kafka_users.v1.CreateKafkaUserResponseBr\n!io.strmprivacy.api.kafka_users.v1P\x01ZKgithub.com/strmprivacy/api-definitions-go/v2/api/kafka_users/v1;kafka_usersb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2.DESCRIPTOR,])




_LISTKAFKAUSERSREQUEST = _descriptor.Descriptor(
  name='ListKafkaUsersRequest',
  full_name='strmprivacy.api.kafka_users.v1.ListKafkaUsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='strmprivacy.api.kafka_users.v1.ListKafkaUsersRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=255,
)


_LISTKAFKAUSERSRESPONSE = _descriptor.Descriptor(
  name='ListKafkaUsersResponse',
  full_name='strmprivacy.api.kafka_users.v1.ListKafkaUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kafka_users', full_name='strmprivacy.api.kafka_users.v1.ListKafkaUsersResponse.kafka_users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=342,
)


_DELETEKAFKAUSERREQUEST = _descriptor.Descriptor(
  name='DeleteKafkaUserRequest',
  full_name='strmprivacy.api.kafka_users.v1.DeleteKafkaUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='strmprivacy.api.kafka_users.v1.DeleteKafkaUserRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=429,
)


_DELETEKAFKAUSERRESPONSE = _descriptor.Descriptor(
  name='DeleteKafkaUserResponse',
  full_name='strmprivacy.api.kafka_users.v1.DeleteKafkaUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=456,
)


_CREATEKAFKAUSERREQUEST = _descriptor.Descriptor(
  name='CreateKafkaUserRequest',
  full_name='strmprivacy.api.kafka_users.v1.CreateKafkaUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kafka_user', full_name='strmprivacy.api.kafka_users.v1.CreateKafkaUserRequest.kafka_user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=542,
)


_CREATEKAFKAUSERRESPONSE = _descriptor.Descriptor(
  name='CreateKafkaUserResponse',
  full_name='strmprivacy.api.kafka_users.v1.CreateKafkaUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kafka_user', full_name='strmprivacy.api.kafka_users.v1.CreateKafkaUserResponse.kafka_user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=629,
)


_GETKAFKAUSERREQUEST = _descriptor.Descriptor(
  name='GetKafkaUserRequest',
  full_name='strmprivacy.api.kafka_users.v1.GetKafkaUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='strmprivacy.api.kafka_users.v1.GetKafkaUserRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=713,
)


_GETKAFKAUSERRESPONSE = _descriptor.Descriptor(
  name='GetKafkaUserResponse',
  full_name='strmprivacy.api.kafka_users.v1.GetKafkaUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kafka_user', full_name='strmprivacy.api.kafka_users.v1.GetKafkaUserResponse.kafka_user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=715,
  serialized_end=797,
)

_LISTKAFKAUSERSREQUEST.fields_by_name['ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAEXPORTERREF
_LISTKAFKAUSERSRESPONSE.fields_by_name['kafka_users'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSER
_DELETEKAFKAUSERREQUEST.fields_by_name['ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSERREF
_CREATEKAFKAUSERREQUEST.fields_by_name['kafka_user'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSER
_CREATEKAFKAUSERRESPONSE.fields_by_name['kafka_user'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSER
_GETKAFKAUSERREQUEST.fields_by_name['ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSERREF
_GETKAFKAUSERRESPONSE.fields_by_name['kafka_user'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._KAFKAUSER
DESCRIPTOR.message_types_by_name['ListKafkaUsersRequest'] = _LISTKAFKAUSERSREQUEST
DESCRIPTOR.message_types_by_name['ListKafkaUsersResponse'] = _LISTKAFKAUSERSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteKafkaUserRequest'] = _DELETEKAFKAUSERREQUEST
DESCRIPTOR.message_types_by_name['DeleteKafkaUserResponse'] = _DELETEKAFKAUSERRESPONSE
DESCRIPTOR.message_types_by_name['CreateKafkaUserRequest'] = _CREATEKAFKAUSERREQUEST
DESCRIPTOR.message_types_by_name['CreateKafkaUserResponse'] = _CREATEKAFKAUSERRESPONSE
DESCRIPTOR.message_types_by_name['GetKafkaUserRequest'] = _GETKAFKAUSERREQUEST
DESCRIPTOR.message_types_by_name['GetKafkaUserResponse'] = _GETKAFKAUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListKafkaUsersRequest = _reflection.GeneratedProtocolMessageType('ListKafkaUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTKAFKAUSERSREQUEST,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.ListKafkaUsersRequest)
  })
_sym_db.RegisterMessage(ListKafkaUsersRequest)

ListKafkaUsersResponse = _reflection.GeneratedProtocolMessageType('ListKafkaUsersResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTKAFKAUSERSRESPONSE,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.ListKafkaUsersResponse)
  })
_sym_db.RegisterMessage(ListKafkaUsersResponse)

DeleteKafkaUserRequest = _reflection.GeneratedProtocolMessageType('DeleteKafkaUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKAFKAUSERREQUEST,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.DeleteKafkaUserRequest)
  })
_sym_db.RegisterMessage(DeleteKafkaUserRequest)

DeleteKafkaUserResponse = _reflection.GeneratedProtocolMessageType('DeleteKafkaUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKAFKAUSERRESPONSE,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.DeleteKafkaUserResponse)
  })
_sym_db.RegisterMessage(DeleteKafkaUserResponse)

CreateKafkaUserRequest = _reflection.GeneratedProtocolMessageType('CreateKafkaUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEKAFKAUSERREQUEST,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.CreateKafkaUserRequest)
  })
_sym_db.RegisterMessage(CreateKafkaUserRequest)

CreateKafkaUserResponse = _reflection.GeneratedProtocolMessageType('CreateKafkaUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEKAFKAUSERRESPONSE,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.CreateKafkaUserResponse)
  })
_sym_db.RegisterMessage(CreateKafkaUserResponse)

GetKafkaUserRequest = _reflection.GeneratedProtocolMessageType('GetKafkaUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKAFKAUSERREQUEST,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.GetKafkaUserRequest)
  })
_sym_db.RegisterMessage(GetKafkaUserRequest)

GetKafkaUserResponse = _reflection.GeneratedProtocolMessageType('GetKafkaUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETKAFKAUSERRESPONSE,
  '__module__' : 'strmprivacy.api.kafka_users.v1.kafka_users_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.kafka_users.v1.GetKafkaUserResponse)
  })
_sym_db.RegisterMessage(GetKafkaUserResponse)


DESCRIPTOR._options = None
_LISTKAFKAUSERSREQUEST.fields_by_name['ref']._options = None
_DELETEKAFKAUSERREQUEST.fields_by_name['ref']._options = None
_GETKAFKAUSERREQUEST.fields_by_name['ref']._options = None

_KAFKAUSERSSERVICE = _descriptor.ServiceDescriptor(
  name='KafkaUsersService',
  full_name='strmprivacy.api.kafka_users.v1.KafkaUsersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=800,
  serialized_end=1337,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListKafkaUsers',
    full_name='strmprivacy.api.kafka_users.v1.KafkaUsersService.ListKafkaUsers',
    index=0,
    containing_service=None,
    input_type=_LISTKAFKAUSERSREQUEST,
    output_type=_LISTKAFKAUSERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetKafkaUser',
    full_name='strmprivacy.api.kafka_users.v1.KafkaUsersService.GetKafkaUser',
    index=1,
    containing_service=None,
    input_type=_GETKAFKAUSERREQUEST,
    output_type=_GETKAFKAUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteKafkaUser',
    full_name='strmprivacy.api.kafka_users.v1.KafkaUsersService.DeleteKafkaUser',
    index=2,
    containing_service=None,
    input_type=_DELETEKAFKAUSERREQUEST,
    output_type=_DELETEKAFKAUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateKafkaUser',
    full_name='strmprivacy.api.kafka_users.v1.KafkaUsersService.CreateKafkaUser',
    index=3,
    containing_service=None,
    input_type=_CREATEKAFKAUSERREQUEST,
    output_type=_CREATEKAFKAUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KAFKAUSERSSERVICE)

DESCRIPTOR.services_by_name['KafkaUsersService'] = _KAFKAUSERSSERVICE

# @@protoc_insertion_point(module_scope)
