# Generated by Django 3.2.7 on 2022-03-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_core', '0002_category_filemodeltemplate_modeltemplate_pathmodeltemplate_stringmodeltemplate'),
        ('simpel_sales', '0004_alter_salessetting_salesorder_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='salesquotation_template',
            field=models.ForeignKey(blank=True, help_text='Custom Quotation template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simpel_core.pathmodeltemplate', verbose_name='Quotation Template'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesorder_template',
            field=models.ForeignKey(blank=True, help_text='Custom Order template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simpel_core.pathmodeltemplate', verbose_name='Order Template'),
        ),
    ]
