# Generated by Django 3.0.10 on 2021-01-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
    ]
