# Generated by Django 3.0.10 on 2021-01-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20210104_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytime',
            options={'ordering': ['start', 'end'], 'verbose_name': 'Delivery Time', 'verbose_name_plural': 'Delivery Times'},
        ),
    ]
