# Generated by Django 3.2.5 on 2021-08-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210122_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverytime'),
        ),
    ]
