# Generated by Django 3.2.5 on 2021-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='target_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
