[tool.poetry]
name = "adrenaline"
version = "1.0.0"
description = "Keep your OS from sleeping (supports Windows and macOS)"
authors = ["Tamas Nepusz <ntamas@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ntamas/adrenaline"
repository = "https://github.com/ntamas/adrenaline"
packages = [
    { include = "adrenaline", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
pyobjc-core = {platform = "darwin", version = "^8.0"}
pyobjc-framework-Cocoa = {platform = "darwin", version = "^8.0"}
jeepney = {platform = "linux", version = "^0.6.0"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
coverage = {extras = ["toml"], version = "^5.2"}
pytest-cov = "^2.11.1"
tox = "^3.23.0"
typing-extensions = {version = "^3.7", python = "<3.8"}

[tool.poetry.scripts]
adrenaline = "adrenaline.__main__:main"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
