[tool.poetry]
authors = ["Peter Yuen <ppeetteerrsx@gmail.com>"]
description = "(Taken from NVIDIA) Replacement for Pytorch's Conv2D and Conv2DTranspose with support for higher-order gradients and disabling unnecessary gradient computations."
documentation = "https://ppeetteerrs.github.io/torch-conv-gradfix"
homepage = "https://github.com/ppeetteerrs/torch-conv-gradfix"
keywords = []
license = "MIT"
name = "torch-conv-gradfix"
readme = "README.md"
repository = "https://github.com/ppeetteerrs/torch-conv-gradfix"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
torch = ">1.7"
numpy = ">=1.21.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.2"
mkdocs-jupyter = "^0.20.1"
mkdocs-material = "^8.2.5"
mkdocstrings-python = "^0.6.6"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[tool.poetry-dynamic-versioning]
enable = false
style = "semver"

[tool.poetry.scripts]
docs = "torch_conv_gradfix:__docs"
serve = "torch_conv_gradfix:__serve"
test = "torch_conv_gradfix:__test"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
