# Generated by Django 3.2.7 on 2022-03-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('simpel_core', '0002_category_filemodeltemplate_modeltemplate_pathmodeltemplate_stringmodeltemplate'),
        ('simpel_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_template', models.ForeignKey(blank=True, help_text='Custom Work Order template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simpel_core.pathmodeltemplate', verbose_name='Work Order Template')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
