# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/type/shared/v1/identifierandstream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:systemathics/apis/type/shared/v1/identifierandstream.proto\x12 systemathics.apis.type.shared.v1\x1a\x1egoogle/protobuf/wrappers.proto\"w\n\x13IdentifierAndStream\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12.\n\x08provider\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0e\n\x06stream\x18\x04 \x01(\tb\x06proto3')



_IDENTIFIERANDSTREAM = DESCRIPTOR.message_types_by_name['IdentifierAndStream']
IdentifierAndStream = _reflection.GeneratedProtocolMessageType('IdentifierAndStream', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIERANDSTREAM,
  '__module__' : 'systemathics.apis.type.shared.v1.identifierandstream_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.type.shared.v1.IdentifierAndStream)
  })
_sym_db.RegisterMessage(IdentifierAndStream)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDENTIFIERANDSTREAM._serialized_start=128
  _IDENTIFIERANDSTREAM._serialized_end=247
# @@protoc_insertion_point(module_scope)
