[tool.poetry]
name = "euporie"
version = "1.3.0"
description = "Euporie is a text-based user interface for running and editing Jupyter notebooks"
authors = ["Josiah Outram Halstead <josiah@halstead.email>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/joouha/euporie"
documentation = "https://euporie.readthedocs.io/en/latest"
keywords = ["jupyter", "ipython", "markdown", "terminal", "notebook"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: Jupyter",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.urls]
"Changelog" = "https://euporie.readthedocs.io/en/latest/pages/changelog.html"
"Bug Tracker" = "https://github.com/joouha/euporie/issues"

[tool.poetry.dependencies]
python = "^3.8"
prompt-toolkit = "^3.0"
nbformat = "^5"
jupyter-client = "^7.1"
rich = "^11"
appdirs = "^1.4"
jsonschema = "^4.4"
pyperclip = "^1.8"
aenum = "^3.1"
flatlatex = "~0.15"
timg = "^1.1"
Pillow = "^9.0"
mtable = {version = "^0.1", optional = true}
html5lib = {version = "^1.1", optional = true}
sympy = {version = "^1.9", optional = true}
imagesize = "^1.3.0"
antlr4-python3-runtime = {version = "^4.9", optional = true}
CairoSVG = {version = "^2.5", optional = true}
img2unicode = {version = "^0.1a8", optional = true}
black = {version = ">=19.3b0", optional = true}
isort = {version = "^5.10.1", optional = true}
ssort = {version = "^0.11.0", optional = true}

[tool.poetry.extras]
all = ["black", "mtable", "html5lib", "CairoSVG"]
formatters = ["black", "isort", "ssort"]
svg-cairosvg = ["CairoSVG"]
latex-sympy = ["sympy", "antlr4-python3-runtime"]
html-mtable = ["mtable", "html5lib"]
images-img2unicode = ["img2unicode"]


[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
flake8 = "^3.9.1"
poetry-publish = "^0.4.1"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"
flake8-bandit = "^2.1.2"
flake8-annotations = "^2.6.2"
flake8-docstrings = "^1.6.0"
mypy = "^0.812"
flake8-isort = "^4.0.0"
darglint = "^1.8.0"
nox-poetry = "^0.9.0"
Sphinx = "^4.4.0"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.0.0"
furo = "^2022.1.2"
black = "^22.1.0"
ssort = "^0.11.0"
bandit = "1.7.2"

[tool.poetry.scripts]
euporie = 'euporie.app:App.launch'

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
