[tool.poetry]
name = "juridecomposer"
version = "0.1.0"
description = ""
authors = ["Roos Bakker <roos.bakker@tno.nl>", "Maaike de Boer <maaike.deboer@tno.nl>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = ">=3.6.1, <3.7"
pandas = "^1.0.5"
nltk = "^3.5"
pattern = "^3.6"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[tool.poetry.scripts]
my-script = "src.juridecomposer.juridecomposer:xml_to_dataframe"

packages = [
    { include = "juridecomposer", from = "src" },
]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
