# Generated by Django 3.2.7 on 2022-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='salesquotation_expiration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Quotation Expiration'),
        ),
    ]
