# Generated by Django 3.2.7 on 2022-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_sales', '0005_auto_20220301_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
