[build-system]
requires = ['pip', 'setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-fem<=v2.8.0.7', 'dune-alugrid<=v2.8.0.7', 'matplotlib', 'triangle', 'scipy', 'sortedcontainers']
build-backend = 'setuptools.build_meta'
