
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T14:57:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc7d9a3577c1f69fbbcd4e4a89c0bc3db6d34620",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
