# Generated by Django 2.2.27 on 2022-02-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0003_auto_20220214_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='djangoldp_circle.Circle'),
        ),
    ]
