# Generated by Django 2.2.27 on 2022-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0007_auto_20220303_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='stockMovement',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='transactionType',
        ),
        migrations.AddField(
            model_name='productstock',
            name='stockAdd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ajout de stock'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='stockRemove',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité commandée'),
        ),
    ]
