# Generated by Django 3.2.12 on 2022-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_sessions', '0006_auto_20201001_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisession',
            name='token_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apisession',
            name='user_agent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
