# Generated by Django 3.0.10 on 2020-12-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201202_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_lock',
            field=models.BooleanField(default=False, help_text='If payment is locked, not all payment methods will be available', verbose_name='payment lock'),
        ),
    ]
