# Generated by Django 3.0.10 on 2020-12-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_payment_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_lock',
        ),
    ]
