# Generated by Django 3.0.10 on 2021-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_payment_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_accepted',
            field=models.BooleanField(default=False, help_text='User accepted to receive newsletter', verbose_name='Newsletter accepted'),
        ),
    ]
