# Generated by Django 3.2.8 on 2021-10-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210903_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='newsletter_accepted',
            new_name='old_newsletter_accepted',
        ),
    ]
