
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T13:04:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8880126c789f4e247e5b12c406111e96120556b4",
 "version": "2.0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
