[build-system]
requires = ["setuptools >= 45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 88
py_version = 310
known_first_party = ["annodize"]
src_paths = ["annodize"]
skip_gitignore = true

[tool.black]
line-length = 88
include = '^/annodize.*\.py' # all .py files
extend-exclude = '''
^/setup.py
|^/docs
|^/dist
'''

[tool.mypy]
python_version = "3.10"
files = 'annodize/**/*.py'
warn_unused_configs = true

[[tool.mypy.overrides]]
module = 'annodize.*'

[tool.pytest.ini_options]
testpaths = ["annodize"]
