repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['-i', '--remove-all-unused-imports']
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
        args: ['-l', '120']
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ['-sl', '--profile', 'black']
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
        args: ['-sl', '--profile', 'black']

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--max-line-length', '120', '--max-doc-length', '120']
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        name: README.md-toc
        files: ^README\.md$
      - id: markdown-toc
        name: configuration.md-toc
        files: .*/configuration\.md$
      - id: markdown-toc
        name: CONTRIBUTE.md-toc
        files: .*/CONTRIBUTE\.md$
