[tool.poetry]
name = "xxyy"
version = "0.1.4"
description = ""
authors = ["laibin <laibin1994@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
