[tool.poetry]
name = "poetry-mkdocs-test"
version = "0.0.1"
description = "Mkdocs plugin that allow to inject external markdown or markdown section from given url"
authors = ["fire1ce <dev@3os.org>"]
license = "MIT"
packages = [
    { include = "external_markdown/plugin.py" },
]

[tool.poetry.dependencies]
python = "^3.6"
mkdocs = "^1.2.3"
requests = "^2.27.1"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
Jinja2 = "^3.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
"mkdocs.plugins" = "external-markdown = external_markdown.plugin:EmbedExternalMarkdown"