[tool.poetry]
name = "lwc_common"
version = "0.4.4-rc2"
description = ""
authors = ["AminuIsrael <israel.aminu@data2bots.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.7,< 3.10"
requests = "^2.27.1"
msedge-selenium-tools = "^3.141.4"
google-cloud-storage = "^2.1.0"
SQLAlchemy = "^1.4.31"
pg8000 = "^1.23.0"
pybigquery = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
