# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/usage/v1/usage_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from strmprivacy.api.entities.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='strmprivacy/api/usage/v1/usage_v1.proto',
  package='strmprivacy.api.usage.v1',
  syntax='proto3',
  serialized_options=b'\n\033io.strmprivacy.api.usage.v1P\001Z?github.com/strmprivacy/api-definitions-go/v2/api/usage/v1;usage',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'strmprivacy/api/usage/v1/usage_v1.proto\x12\x18strmprivacy.api.usage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-strmprivacy/api/entities/v1/entities_v1.proto\"\xdc\x01\n\x1aGetStreamEventUsageRequest\x12\x33\n\x03ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRef\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08interval\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"\x94\x01\n\x1bGetStreamEventUsageResponse\x12\x33\n\x03ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRef\x12@\n\x07windows\x18\x02 \x03(\x0b\x32/.strmprivacy.api.entities.v1.WindowedEventCount2\x93\x01\n\x0cUsageService\x12\x82\x01\n\x13GetStreamEventUsage\x12\x34.strmprivacy.api.usage.v1.GetStreamEventUsageRequest\x1a\x35.strmprivacy.api.usage.v1.GetStreamEventUsageResponseB`\n\x1bio.strmprivacy.api.usage.v1P\x01Z?github.com/strmprivacy/api-definitions-go/v2/api/usage/v1;usageb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2.DESCRIPTOR,])




_GETSTREAMEVENTUSAGEREQUEST = _descriptor.Descriptor(
  name='GetStreamEventUsageRequest',
  full_name='strmprivacy.api.usage.v1.GetStreamEventUsageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageRequest.start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageRequest.end_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interval', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageRequest.interval', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=402,
)


_GETSTREAMEVENTUSAGERESPONSE = _descriptor.Descriptor(
  name='GetStreamEventUsageResponse',
  full_name='strmprivacy.api.usage.v1.GetStreamEventUsageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageResponse.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='windows', full_name='strmprivacy.api.usage.v1.GetStreamEventUsageResponse.windows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=553,
)

_GETSTREAMEVENTUSAGEREQUEST.fields_by_name['ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_GETSTREAMEVENTUSAGEREQUEST.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETSTREAMEVENTUSAGEREQUEST.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETSTREAMEVENTUSAGEREQUEST.fields_by_name['interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_GETSTREAMEVENTUSAGERESPONSE.fields_by_name['ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_GETSTREAMEVENTUSAGERESPONSE.fields_by_name['windows'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._WINDOWEDEVENTCOUNT
DESCRIPTOR.message_types_by_name['GetStreamEventUsageRequest'] = _GETSTREAMEVENTUSAGEREQUEST
DESCRIPTOR.message_types_by_name['GetStreamEventUsageResponse'] = _GETSTREAMEVENTUSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStreamEventUsageRequest = _reflection.GeneratedProtocolMessageType('GetStreamEventUsageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMEVENTUSAGEREQUEST,
  '__module__' : 'strmprivacy.api.usage.v1.usage_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.usage.v1.GetStreamEventUsageRequest)
  })
_sym_db.RegisterMessage(GetStreamEventUsageRequest)

GetStreamEventUsageResponse = _reflection.GeneratedProtocolMessageType('GetStreamEventUsageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMEVENTUSAGERESPONSE,
  '__module__' : 'strmprivacy.api.usage.v1.usage_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.usage.v1.GetStreamEventUsageResponse)
  })
_sym_db.RegisterMessage(GetStreamEventUsageResponse)


DESCRIPTOR._options = None

_USAGESERVICE = _descriptor.ServiceDescriptor(
  name='UsageService',
  full_name='strmprivacy.api.usage.v1.UsageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=556,
  serialized_end=703,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStreamEventUsage',
    full_name='strmprivacy.api.usage.v1.UsageService.GetStreamEventUsage',
    index=0,
    containing_service=None,
    input_type=_GETSTREAMEVENTUSAGEREQUEST,
    output_type=_GETSTREAMEVENTUSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USAGESERVICE)

DESCRIPTOR.services_by_name['UsageService'] = _USAGESERVICE

# @@protoc_insertion_point(module_scope)
