# Version file autogenerated by the build process
version = '0.10.0-alpha1'
build = 1047
vcs_info = 'Git SHA1 1ef6143f committed on 2022-03-23'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.10.0-alpha1"\nKSCONF_BUILD="1047"\nKSCONF_VCS_INFO="Git SHA1 1ef6143f committed on 2022-03-23"')
