[tool.poetry]
name = "microlib"
version = "1.8.0"
description = "Collection of various useful tools."
authors = ["Nicolas Hainaux <nh.techn@gmail.com>"]
readme = 'README.rst'

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = { version = "^3.1", python = "3.6.* || 3.7.*" }
toml = "^0.10.2"
click = "^8.0.1"
blessed = "^1.18.1"
intspan = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
pytest-mock = "^3.3.1"
coverage = "^5.3"
coveralls = "^2.2.0"
pyfakefs = "^4.5.0"

[build-system]
# requires = ["poetry-core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"
