from mos import pause
from mos import rndint
from mos import read
from mos import edit
from mos import errsrch
from mos import help
from mos import clear
from mos import helpFunc
from mos import help
