
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T17:56:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "dad95fe4b5e4df1a8d31e26099e43c5b325d668e",
 "version": "2022.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
