[tool.poetry]
name = "deploy_k8s_cli"
version = "0.1.0"
description = "Command line interface to deploy a Kubernetes cluster on OpenStack"
authors = ["Alexis Janero Moliner <ajanerom@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
ansible-runner = "^2.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
