# Generated by Django 3.0.10 on 2020-12-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20201005_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='container_count',
            field=models.PositiveIntegerField(blank=True, help_text='Amount of Container (eg. bottles) of the Product.', null=True, verbose_name='Container Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deposit (import)'),
        ),
    ]
