# Generated by Django 3.0.10 on 2020-12-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20201202_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='container_count',
        ),
    ]
