# Generated by Django 3.0.10 on 2020-12-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20201208_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='volume in ml(optional)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='weight in g(optional)'),
        ),
    ]
