# Generated by Django 3.0.10 on 2020-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20201208_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Box that contains the product. You can create one in deposit menu.', max_digits=12, null=True, verbose_name='Box deposit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Import field', max_digits=12, null=True, verbose_name='Deposit sum'),
        ),
    ]
