# Generated by Django 3.0.10 on 2020-12-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20201209_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_deposit',
        ),
        migrations.AddField(
            model_name='product',
            name='reusable',
            field=models.BooleanField(default=False, help_text='Is this container reusable or one-way', verbose_name='Is reusable'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('12er', '12er'), ('chep', 'chep'), ('5er', '5er'), ('KA', 'KA'), ('6er', '6er'), ('Fa', 'Fa'), ('BIB', 'BIB'), ('Fl', 'Fl'), ('FL', 'FL'), ('Stk', 'Stk'), ('Dose', 'Dose'), ('Pre', 'Pre')], max_length=4, null=True, verbose_name='Packaging unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='This field overwrites the calculated deposit', max_digits=12, null=True, verbose_name='Deposit sum'),
        ),
    ]
