# Generated by Django 3.0.10 on 2020-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20201209_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='volume in (l)(optional)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='weight (kg)(optional)'),
        ),
    ]
