# Generated by Django 3.0.10 on 2020-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20201209_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='container_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Container Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reusable',
            field=models.BooleanField(default=False, verbose_name='Is reusable'),
        ),
    ]
