# Generated by Django 3.0.10 on 2020-12-09 22:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20201209_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Specialprice'),
        ),
        migrations.AddField(
            model_name='product',
            name='vpefactor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Grundpreis Faktor'),
        ),
        migrations.AddField(
            model_name='product',
            name='vpeid',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1l'), (2, '1.5l'), (3, '0.7l'), (4, '1KG')], null=True, verbose_name='Grundpreis Einheit'),
        ),
    ]
