# Generated by Django 3.0.10 on 2020-12-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20201211_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reusable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
    ]
