# Generated by Django 3.0.10 on 2020-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20201213_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_box',
            field=models.BooleanField(blank=True, default=False, help_text='Does this Product has a box (for box discount)?', null=True, verbose_name='Has box'),
        ),
    ]
