# Generated by Django 3.0.10 on 2020-12-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_product_has_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_box',
            field=models.BooleanField(blank=True, help_text='Does this Product has a box (for box discount)?', null=True, verbose_name='Has box'),
        ),
    ]
