# Generated by Django 3.0.10 on 2020-12-23 10:34

from django.db import migrations
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20201217_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
