# Generated by Django 3.0.10 on 2021-01-07 15:00

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_product_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
