# Generated by Django 3.0.10 on 2021-01-15 14:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_category_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Special price'),
        ),
    ]
