# Generated by Django 3.0.10 on 2021-01-25 15:39

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20210115_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
