# Generated by Django 3.1.6 on 2021-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_auto_20210125_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='Positive and negative Priority for default ordering of the Results', verbose_name='Priority'),
        ),
    ]
