# Generated by Django 3.1.6 on 2021-05-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_product_priority'),
        ('offer', '0020_migrate_special_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price_start',
        ),
    ]
