# Generated by Django 3.1.6 on 2021-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20210519_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_reference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
