# Generated by Django 3.1.6 on 2021-06-15 14:52

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_product_external_reference'),
    ]

    operations = [
        TrigramExtension(),
    ]
