# Generated by Django 3.2.5 on 2021-08-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20210816_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
