# Generated by Django 3.2.10 on 2022-01-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_avoid_leading_zeros_in_upc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurzbezeichnung des Herstellers', max_length=100, unique=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=250, null=True, verbose_name='Adresszeile 1')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='reusability',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'EINWEG'), (1, 'MEHRWEG')], null=True, verbose_name='Wiederverwertbarkeit'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.manufacturer'),
        ),
    ]
