# Generated by Django 3.2.10 on 2022-01-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0054_reusability_and_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ManyToManyField(help_text='Zuweisung von Kategorien zu einer Seite', related_name='categories', to='sites.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='product',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Diese Benutzer dürfen das Produkt ohne Überprüfung editieren', related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Product Editoren'),
        ),
        migrations.CreateModel(
            name='SiteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
