# Generated by Django 3.1.6 on 2021-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_create_shipping_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderanditemcharges',
            options={'ordering': ['display_order'], 'verbose_name': 'Order and Item Charge', 'verbose_name_plural': 'Order and Item Charges'},
        ),
    ]
