# Generated by Django 3.2.5 on 2021-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_orderanditemcharges_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderanditemcharges',
            name='form_fields',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No form'), (1, 'Floor'), (2, 'Delivery'), (3, 'Floor and delivery'), (4, 'Date'), (5, 'Date and time')], default=0, verbose_name='Form fields'),
        ),
    ]
