# Generated by Django 3.2.8 on 2021-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_alter_orderanditemcharges_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderanditemcharges',
            name='next_day_limit',
            field=models.TimeField(blank=True, help_text='Delivery to the next day possible until this time', null=True, verbose_name='Next day limit'),
        ),
    ]
