# Generated by Django 3.2.12 on 2022-02-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('in', 'include'), ('sw', 'switch')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='热键', max_length=10)),
                ('action', models.TextField(help_text='动作')),
                ('help_text', models.TextField(help_text='热键说明')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohotkey.script')),
            ],
        ),
    ]
