# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/credentials/v1/credentials_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from strmprivacy.api.entities.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='strmprivacy/api/credentials/v1/credentials_v1.proto',
  package='strmprivacy.api.credentials.v1',
  syntax='proto3',
  serialized_options=b'\n!io.strmprivacy.api.credentials.v1P\001ZKgithub.com/strmprivacy/api-definitions-go/v2/api/credentials/v1;credentials',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3strmprivacy/api/credentials/v1/credentials_v1.proto\x12\x1estrmprivacy.api.credentials.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a-strmprivacy/api/entities/v1/entities_v1.proto\"Y\n\x16ListCredentialsRequest\x12?\n\nstream_ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRefB\x03\xe0\x41\x02\"X\n\x17ListCredentialsResponse\x12=\n\x0b\x63redentials\x18\x01 \x03(\x0b\x32(.strmprivacy.api.entities.v1.Credentials\",\n\x17\x44\x65leteCredentialRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x1a\n\x18\x44\x65leteCredentialResponse\")\n\x14GetCredentialRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"U\n\x15GetCredentialResponse\x12<\n\ncredential\x18\x01 \x01(\x0b\x32(.strmprivacy.api.entities.v1.Credentials\"U\n\x17\x43reateCredentialRequest\x12:\n\nstream_ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRef\"Y\n\x18\x43reateCredentialResponse\x12=\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32(.strmprivacy.api.entities.v1.Credentials2\xa7\x04\n\x12\x43redentialsService\x12\x82\x01\n\x0fListCredentials\x12\x36.strmprivacy.api.credentials.v1.ListCredentialsRequest\x1a\x37.strmprivacy.api.credentials.v1.ListCredentialsResponse\x12|\n\rGetCredential\x12\x34.strmprivacy.api.credentials.v1.GetCredentialRequest\x1a\x35.strmprivacy.api.credentials.v1.GetCredentialResponse\x12\x85\x01\n\x10\x43reateCredential\x12\x37.strmprivacy.api.credentials.v1.CreateCredentialRequest\x1a\x38.strmprivacy.api.credentials.v1.CreateCredentialResponse\x12\x85\x01\n\x10\x44\x65leteCredential\x12\x37.strmprivacy.api.credentials.v1.DeleteCredentialRequest\x1a\x38.strmprivacy.api.credentials.v1.DeleteCredentialResponseBr\n!io.strmprivacy.api.credentials.v1P\x01ZKgithub.com/strmprivacy/api-definitions-go/v2/api/credentials/v1;credentialsb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2.DESCRIPTOR,])




_LISTCREDENTIALSREQUEST = _descriptor.Descriptor(
  name='ListCredentialsRequest',
  full_name='strmprivacy.api.credentials.v1.ListCredentialsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_ref', full_name='strmprivacy.api.credentials.v1.ListCredentialsRequest.stream_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=256,
)


_LISTCREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='ListCredentialsResponse',
  full_name='strmprivacy.api.credentials.v1.ListCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='strmprivacy.api.credentials.v1.ListCredentialsResponse.credentials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=346,
)


_DELETECREDENTIALREQUEST = _descriptor.Descriptor(
  name='DeleteCredentialRequest',
  full_name='strmprivacy.api.credentials.v1.DeleteCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='strmprivacy.api.credentials.v1.DeleteCredentialRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=392,
)


_DELETECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='DeleteCredentialResponse',
  full_name='strmprivacy.api.credentials.v1.DeleteCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=420,
)


_GETCREDENTIALREQUEST = _descriptor.Descriptor(
  name='GetCredentialRequest',
  full_name='strmprivacy.api.credentials.v1.GetCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='strmprivacy.api.credentials.v1.GetCredentialRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=463,
)


_GETCREDENTIALRESPONSE = _descriptor.Descriptor(
  name='GetCredentialResponse',
  full_name='strmprivacy.api.credentials.v1.GetCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='strmprivacy.api.credentials.v1.GetCredentialResponse.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=550,
)


_CREATECREDENTIALREQUEST = _descriptor.Descriptor(
  name='CreateCredentialRequest',
  full_name='strmprivacy.api.credentials.v1.CreateCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_ref', full_name='strmprivacy.api.credentials.v1.CreateCredentialRequest.stream_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=637,
)


_CREATECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='CreateCredentialResponse',
  full_name='strmprivacy.api.credentials.v1.CreateCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='strmprivacy.api.credentials.v1.CreateCredentialResponse.credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=728,
)

_LISTCREDENTIALSREQUEST.fields_by_name['stream_ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_LISTCREDENTIALSRESPONSE.fields_by_name['credentials'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._CREDENTIALS
_GETCREDENTIALRESPONSE.fields_by_name['credential'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._CREDENTIALS
_CREATECREDENTIALREQUEST.fields_by_name['stream_ref'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_CREATECREDENTIALRESPONSE.fields_by_name['credentials'].message_type = strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._CREDENTIALS
DESCRIPTOR.message_types_by_name['ListCredentialsRequest'] = _LISTCREDENTIALSREQUEST
DESCRIPTOR.message_types_by_name['ListCredentialsResponse'] = _LISTCREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteCredentialRequest'] = _DELETECREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['DeleteCredentialResponse'] = _DELETECREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['GetCredentialRequest'] = _GETCREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['GetCredentialResponse'] = _GETCREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['CreateCredentialRequest'] = _CREATECREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['CreateCredentialResponse'] = _CREATECREDENTIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListCredentialsRequest = _reflection.GeneratedProtocolMessageType('ListCredentialsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTCREDENTIALSREQUEST,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.ListCredentialsRequest)
  })
_sym_db.RegisterMessage(ListCredentialsRequest)

ListCredentialsResponse = _reflection.GeneratedProtocolMessageType('ListCredentialsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCREDENTIALSRESPONSE,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.ListCredentialsResponse)
  })
_sym_db.RegisterMessage(ListCredentialsResponse)

DeleteCredentialRequest = _reflection.GeneratedProtocolMessageType('DeleteCredentialRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECREDENTIALREQUEST,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.DeleteCredentialRequest)
  })
_sym_db.RegisterMessage(DeleteCredentialRequest)

DeleteCredentialResponse = _reflection.GeneratedProtocolMessageType('DeleteCredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETECREDENTIALRESPONSE,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.DeleteCredentialResponse)
  })
_sym_db.RegisterMessage(DeleteCredentialResponse)

GetCredentialRequest = _reflection.GeneratedProtocolMessageType('GetCredentialRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCREDENTIALREQUEST,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.GetCredentialRequest)
  })
_sym_db.RegisterMessage(GetCredentialRequest)

GetCredentialResponse = _reflection.GeneratedProtocolMessageType('GetCredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCREDENTIALRESPONSE,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.GetCredentialResponse)
  })
_sym_db.RegisterMessage(GetCredentialResponse)

CreateCredentialRequest = _reflection.GeneratedProtocolMessageType('CreateCredentialRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECREDENTIALREQUEST,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.CreateCredentialRequest)
  })
_sym_db.RegisterMessage(CreateCredentialRequest)

CreateCredentialResponse = _reflection.GeneratedProtocolMessageType('CreateCredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECREDENTIALRESPONSE,
  '__module__' : 'strmprivacy.api.credentials.v1.credentials_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.credentials.v1.CreateCredentialResponse)
  })
_sym_db.RegisterMessage(CreateCredentialResponse)


DESCRIPTOR._options = None
_LISTCREDENTIALSREQUEST.fields_by_name['stream_ref']._options = None

_CREDENTIALSSERVICE = _descriptor.ServiceDescriptor(
  name='CredentialsService',
  full_name='strmprivacy.api.credentials.v1.CredentialsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=731,
  serialized_end=1282,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListCredentials',
    full_name='strmprivacy.api.credentials.v1.CredentialsService.ListCredentials',
    index=0,
    containing_service=None,
    input_type=_LISTCREDENTIALSREQUEST,
    output_type=_LISTCREDENTIALSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCredential',
    full_name='strmprivacy.api.credentials.v1.CredentialsService.GetCredential',
    index=1,
    containing_service=None,
    input_type=_GETCREDENTIALREQUEST,
    output_type=_GETCREDENTIALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCredential',
    full_name='strmprivacy.api.credentials.v1.CredentialsService.CreateCredential',
    index=2,
    containing_service=None,
    input_type=_CREATECREDENTIALREQUEST,
    output_type=_CREATECREDENTIALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteCredential',
    full_name='strmprivacy.api.credentials.v1.CredentialsService.DeleteCredential',
    index=3,
    containing_service=None,
    input_type=_DELETECREDENTIALREQUEST,
    output_type=_DELETECREDENTIALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREDENTIALSSERVICE)

DESCRIPTOR.services_by_name['CredentialsService'] = _CREDENTIALSSERVICE

# @@protoc_insertion_point(module_scope)
