[tool.poetry]
name = "stefan-utils"
version = "0.0.2"
description = ""
authors = ["Stefan Bader <baderstefan@gmx.de>"]
packages = [
    {include="src/main/python/stefan_utils"}
]

[tool.poetry.dependencies]
python = "^3.10"
python-json-logger = "^2.0.2"
numpy = "^1.22.3"
pandas = "^1.4.1"
pyarrow = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pylint = "^2.12.2"
mypy = "^0.941"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
