# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from action_pb2 import (
    ActionInvocationStatusValue as action_pb2___ActionInvocationStatusValue,
    ActionParams as action_pb2___ActionParams,
    ThirdPartyActionInvocationResponse as action_pb2___ThirdPartyActionInvocationResponse,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from integration_source_pb2 import (
    IntegrationSourceValue as integration_source_pb2___IntegrationSourceValue,
)

from related_data_pb2 import (
    RelatedData as related_data_pb2___RelatedData,
    RelatedDataTypeValue as related_data_pb2___RelatedDataTypeValue,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetActionsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___GetActionsRequest = GetActionsRequest

class InvokeActionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    action_canonical_id: typing___Text = ...
    entity_canonical_id: typing___Text = ...

    @property
    def override_action_params(self) -> action_pb2___ActionParams: ...

    def __init__(self,
        *,
        action_canonical_id : typing___Optional[typing___Text] = None,
        entity_canonical_id : typing___Optional[typing___Text] = None,
        override_action_params : typing___Optional[action_pb2___ActionParams] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"override_action_params",b"override_action_params"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_canonical_id",b"action_canonical_id",u"entity_canonical_id",b"entity_canonical_id",u"override_action_params",b"override_action_params"]) -> None: ...
type___InvokeActionRequest = InvokeActionRequest

class InvokeActionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    action_invocation_status: action_pb2___ActionInvocationStatusValue = ...

    @property
    def raw_response_payload(self) -> action_pb2___ThirdPartyActionInvocationResponse: ...

    def __init__(self,
        *,
        action_invocation_status : typing___Optional[action_pb2___ActionInvocationStatusValue] = None,
        raw_response_payload : typing___Optional[action_pb2___ThirdPartyActionInvocationResponse] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"raw_response_payload",b"raw_response_payload"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_invocation_status",b"action_invocation_status",u"raw_response_payload",b"raw_response_payload"]) -> None: ...
type___InvokeActionResponse = InvokeActionResponse

class GetRelatedDataRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    related_data_type: related_data_pb2___RelatedDataTypeValue = ...
    source: integration_source_pb2___IntegrationSourceValue = ...

    def __init__(self,
        *,
        related_data_type : typing___Optional[related_data_pb2___RelatedDataTypeValue] = None,
        source : typing___Optional[integration_source_pb2___IntegrationSourceValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"related_data_type",b"related_data_type",u"source",b"source"]) -> None: ...
type___GetRelatedDataRequest = GetRelatedDataRequest

class GetRelatedDataResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def related_data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[related_data_pb2___RelatedData]: ...

    def __init__(self,
        *,
        related_data : typing___Optional[typing___Iterable[related_data_pb2___RelatedData]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"related_data",b"related_data"]) -> None: ...
type___GetRelatedDataResponse = GetRelatedDataResponse
