# Generated by Django 3.2.7 on 2022-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Can be Sold'),
        ),
    ]
