# Generated by Django 3.2.7 on 2022-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_products', '0003_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Enable comments'),
        ),
    ]
