[tool.poetry]
name = "poetry-pyinvoke-plugin"
version = "0.1.2"
description = "A plugin for poetry that allows you to execute scripts defined in your tasks.py using pyinvoke. Inspired by poetry-exec-plugin."
authors = ["neozenith"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/neozenith/poetry-pyinvoke-plugin"
repository = "https://github.com/neozenith/poetry-pyinvoke-plugin"

[tool.poetry.dependencies]
poetry = "^1.2.0.a2"
python = "^3.7"
simple-chalk = "^0.1.0"
toml = "^0.10.2"
invoke = "^1.6.0"

[tool.poetry.dev-dependencies]
black = "^21.7-beta.0"
flake8 = "^3.9.2"
mypy = "^0.910"
pytest = "^6.2.4"
pytest-mock = "^3.6.1"
types-toml = "^0.1.5"

[tool.poetry-exec-plugin.commands]
lint = "flake8 && black --check . && mypy ."
test = "pytest"
test-script = "echo Hello World" # Used in tests

[tool.poetry.plugins."poetry.application.plugin"]
invoke = "poetry_pyinvoke_plugin.plugin:InvokePlugin"
inv = "poetry_pyinvoke_plugin.plugin:InvPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
