from mel import on_run
from mel import melhelp
from mel import helpFunc
from mel import clearConsole
from mel import game
from mel import rand
from mel import wait
from mel import nput
from mel import split
from mel import lines
from mel import char
from mel import file
from mel import get
from mel import edit
from mel import read
from mel import __init__
from mel import reset
from mel import dim
from mel import red
from mel import blue
from mel import green
from mel import yellow
from mel import magenta
from mel import black
from mel import white
from mel import cyan
from mel import red
from mel import blue
from mel import green
from mel import yellow
from mel import magenta
from mel import black
from mel import white
from mel import cyan
from mel import compress
from mel import expand
from mel import config
