
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-25T11:10:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d69a7370c9c82d995abd12d45fb6160f7e5ceba0",
 "version": "0.7.1.post.dev457"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
