# Generated by Django 3.0.10 on 2020-12-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('order', '0011_auto_20200801_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Delivery'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choose Floor'),
        ),
    ]
