# Generated by Django 3.0.10 on 2020-12-06 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20201202_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(-2, '2nd basement'), (-1, '1st basement'), (0, 'Ground floor'), (1, '1st floor'), (2, '2nd floor')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
    ]
