# Generated by Django 3.0.10 on 2020-12-17 17:31

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201206_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(-2, '2nd basement'), (-1, '1st basement'), (0, 'Ground floor'), (1, '1st floor'), (2, '2nd floor')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
