# Generated by Django 3.0.10 on 2021-01-14 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20201217_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(2, '2nd floor'), (1, '1st floor'), (0, 'Erdgeschoss / Aufzug vorhanden'), (-1, '1st basement'), (-2, '2nd basement')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(2, '2nd floor'), (1, '1st floor'), (0, 'Erdgeschoss / Aufzug vorhanden'), (-1, '1st basement'), (-2, '2nd basement')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
    ]
