# Generated by Django 3.0.10 on 2021-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210114_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_deposit_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Position Pfand (ohne Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line_deposit_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Position Pfand (inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line_price_excl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Position ohne Pfand(ohne Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line_price_incl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Position ohne Pfand(inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='unit_deposit_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Artikel Pfand (ohne Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='unit_deposit_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Artikel Pfand (inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='unit_price_excl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Artikel ohne Pfand(ohne Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='unit_price_incl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Artikel ohne Pfand(inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_deposit_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pfand (ohne Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_deposit_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pfand (inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_excl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamt ohne Pfand(inkl. Steuer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_incl_tax_excl_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamt ohne Pfand(ohne Steuer)'),
            preserve_default=False,
        ),
    ]
