# Generated by Django 3.0.10 on 2021-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210116_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='sage_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Sage Kunden ID'),
        ),
    ]
