# Generated by Django 3.0.10 on 2021-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_billingaddress_sage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Payment provider code'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=128, verbose_name='Payment provider'),
        ),
    ]
