# Generated by Django 3.0.10 on 2021-01-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210116_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line_deposit_excl_tax',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_deposit_incl_tax',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_price_excl_tax_excl_deposit',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_price_incl_tax_excl_deposit',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_price_excl_tax_excl_deposit',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_price_incl_tax_excl_deposit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_excl_tax_excl_deposit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_incl_tax_excl_deposit',
        ),
    ]
