# Generated by Django 3.0.10 on 2021-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20210118_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
    ]
