# Generated by Django 3.0.10 on 2021-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20210202_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='sage_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Sage Kunden ID'),
        ),
    ]
