# Generated by Django 3.1.6 on 2021-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_shippingaddress_sage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='is_company',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gewerblicher Kunde?'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_company',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gewerblicher Kunde?'),
        ),
    ]
