# Generated by Django 3.0.10 on 2021-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20210208_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='cost_center',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostenstelle'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='cost_center',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostenstelle'),
        ),
    ]
