# Generated by Django 3.0.10 on 2021-02-14 11:08

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20210210_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='order',
            name='lines_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Account owner'),
        ),
    ]
