# Generated by Django 3.1.6 on 2021-04-25 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20210216_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(2, '2. Obergeschoss'), (1, '1. Obergeschoss'), (0, 'Erdgeschoss / Aufzug vorhanden'), (-1, '1. Untergeschoss'), (-2, '2. Untergeschoss')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(2, '2. Obergeschoss'), (1, '1. Obergeschoss'), (0, 'Erdgeschoss / Aufzug vorhanden'), (-1, '1. Untergeschoss'), (-2, '2. Untergeschoss')], null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Choose Floor'),
        ),
    ]
