# Generated by Django 3.1.6 on 2021-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20210425_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choose Floor'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choose Floor'),
        ),
    ]
