# Generated by Django 3.1.6 on 2021-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20210605_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_reference',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Shipping reference'),
        ),
    ]
