# Generated by Django 3.2.5 on 2021-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_shipping_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_reference',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Shipping reference'),
        ),
    ]
