# Generated by Django 3.2.11 on 2022-02-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('order', '0031_alter_order_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='Order number'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('site', 'number')},
        ),
    ]
