[tool.poetry]
name = "gibbs_sampler"
version = "0.2.0"
description = "Gibbs Sampler for motif discovery"
authors = ["Monty Python"]
license = "CC0 v1.0 Universal"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
bio = "^1.3.3"
numpy = "^1.22.3"
weblogo = "^3.7.9"

[tool.poetry.dev-dependencies]
myst-nb = {version = "^0.13.2", python = "^3.9"}
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gibbs_sampler = 'gibbs_sampler.gibbs_sampler:main'