
VERSION = "0.0.02"
'''                                                                                                                                                                                                                                                                                                                                  
^YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.                                                                                                                                                                                                                                                                                                    
^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5:                                                                                                                                                                                                                                                                                                    
^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPP?:::::::::::::::::::::::::::::::::::::::::::::JPPPPPPPPP5Y?!~~~^:::::::::::::::::::::::^YPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPP~                                             !PPPPPPY7:.                               ?PPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPP!                                             !PPP57:                                   ?PPPPP5.                                                    ...                                                      ~7^                                                                                                                                                                                    
^PPPPPP!                                             !PP?.                                     ?PPPPP5.                                                  ^?5PJ.                                                    .5G57.                                                                                                                 ..                 ^7~                                           
^PPPPPP!                                             7Y:                                       ?PPPPP5.                                                  ?5GGY.  :~^:                                              :PGPJ:                                                                            .                                   :Y5~.              .7P5!                                          
^PPPPPP!                                             :.                                        ?PPPPP5.                                                 .J5PP7  :JGPP^.                                           .^PG57.                                                   ~7YYJ~.              .!?Y?^                                 :?GG?^              :YPPY.                                         
^PPPPPP!                                                                                       ?PPPPP5.                                ..:::.      ..   :5PPP! .75P5?:                                            .!GGPY:                                                 ~?PPGGG5J.             7GGGY~                                .!5PGY7             .~PPPY.                                         
^PPPPPP!                                                                                       ?PPPPP5.                            ^~?YPPGGGP5!. ^7GP~^:?GGP?^~JGP!:                                              ^?GGP5^..:^~!^.                                      .~?GGGGGGG5Y.      ..     ?GPGY~                                ^?PPG5J             .!PPPY.                                         
^PPPPPP!                                                                                       ?PPPPP5.                         .:!PPGGGGGGGGPY^ 7YGGPPPGGGPYJPGGP7^.                                             ^?GGPPYJYPPPGPY!.                                  ^!YPGGGGGGPGJ~    .~?YYYJ~^^5GPGY^                                ~JGGG5?             ^7GPPP^                                         
^PPPPPP!                                                                                       ?PPPPP5.                        :!PPGGGG5YJY5PP?: ~?GGGGGGGGGGGGGGGPJ^                                 ^?7:.       7YGGGGGGP5Y5PGG5Y:                                 YPGGGGGGGPPJ^.    .~YGGGGPPPPGGG?.                                ?5GGGP5~:           ~JGGGGY7!!^.                                    
^PPPPPP!                                                                                       ?PPPPP5.                         .?5GGPY:. .^PP?: .^YPGGGGGGGGGGGG5!:                                 ^JGPP!.    .~5PPPPPY7:.^7PPGGGY.                                YPGGGGGGGP5:        :55YJ~7?PGGG7.                               .Y5GGGPPP5^.         7YGGGGGGGGPJ                                    
^PPPPPP~                                                                                       ?PPPPP5.                          !YGPP~    .PP?:   :YGGGGGGGGG5J~:....                              .Y5GGG5J^^7?5PGGGG5!.   7YGGGGG5:                                Y5P5Y775PPP!:        ..   .~PGPG7.                               .Y5GGGGGGP:         .J5GGGGGGGGPJ                                    
^PPPPPP!                                                                                       ?PPPPP5.                          ~YGPG?.  .^PP?^ .:!5GGGGGP55P7~^!5557^                            :7PPPGPGGPPGGGGGGGG7   .!5PPGPY?^                                 .:^:. .YPGPPY7~^:.        .~PGPG7.                               :PPGGGGGG?        .~7PPPGGGGG5Y~.                                    
^PPPPPP?                                                                                       ?PPPPP5.                          .?GGPGP555PPP7?JPGGGGGGGG?~7YGPGP7~:                              ?PGGGGGGGGGP5?YPPGG~  .YGGGPY^.                                        .~5PGGGGGGPY?        .~PGPG7.                             .^JGGGGGP57:     ^?5PGGGGGGGPY~:                                       
^PPPPPPJ                                                     .:~!?JYJJJJJJJJJJJJJJJJJJJJJJJJJJY5PPPPP5.                          .7GGGGGPP5PGP7~^Y55PGGGGGPPP55PG5:                               .YGGGGGGGGP5~: ~PGPP:  .J5YJ!.                                         .?5PGGGGPGJ~:.:~^^^.  .~PGPG7.                        ..~!JYPGGGGGG7^     :~PGGGGGGGG5J~.                                         
^PPPPPP?                                                  .~J5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                          :?GGGP?~.:~PP!: .:^JGGG5J7~::7JGG5?~..                           :PGGGGGGGGJ^   !GGPY.    ..                                 ...    :^7J5PGGGGPPY7.  .YPPPPYJ.:^PGPG7.                     .!JY5PPGGGGGGPG5.      .^JYPPGGGGG~.                                           
^PPPPPP?                                                .?5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                          ~YGPGY.  .^PP~:.!?YPG5Y: ..~7555J5PG5Y7~^::.                     ^PGGGGGGGP^   .?GGY7                                      ^7Y55J??YPPGGGGGGGPP7:   ^??!YGPJ?::^PGGG?:..:^~~^.            :!GGGGGGGGPPGGPGJ          .:^5GGGG.                                            
^PPPPPP?                                               ~5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                          75GGGJ   ^7GP55PGGGGG?^.!?5PG5J^..^JPGGGPPP5YYY!                 .YGGGGGG5Y.   :JGG7: .!?JJ!^  ..^^^^^^^^^..              .YPGGGGGGGGGGGGGGGGP5:. .?7~ .7!^   .~PGGGP555PPGGG5~.          ~JGGGGGG5J~7PPPGJ  :~:.       YGPGG:^7?7^.                                      
^PPPPPP?                                              7PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                         .Y5GGG? .^YPGPJ7^?YGGPY???YPGGJ!     ^!Y5555YYYY7.                 75GGGGG?~    !5GP!:^JPGGGPPYJ55PPPPPPPPPPY:.            .5PGGGGGGPYJ?5PGGGGPP!^:??: ^J~    .~?PGGGGGGGGPP5Y7.           .~55557~.  .Y5GGY::Y5^.      .5GGGG5PGGG5J.                                     
^PPPPPP?                                             ^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                        .^PPGGGPY5PPPPP7^ 7YGGGP5:.!YGGJ!.                                   .!77!^.   .^YPGGP5PGGGGGGGGGGGGGGGGGGGGGP5?.           .J5GGGY?~:  :JPGGGGGGPPPJ:^!J^.:~J5PPPGGGGPPY?^:.                           J5GGPPPG?.      :!GGGGGGGGGPJ!                                      
^PPPPPP?                                             ?PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                        :!PPGGGGG5?7?GPJ?7PPGGPPP55PGGG5Y7.                                          :~JYGGGGGGGPGGGGGGGGPPPP55YJJ!!~^..             :!YJ!.    .?5GGGGGGGPPP5Y5G57?PPGGGGPGGGG5?.                              .J5GGGGP?^!?J~:.:J5GGPY?PPGP7:                                       
^PPPPPP?                                             YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                        ~JGGGGGP7^ .~GPPPPGGPPGPP775GGPJ7: ..:::.                                :~7JPPGGPGGGGGGGGGGGGPP?^^::...                              ^7PPGGGGGGP?7!PGGGGGGGGYJ!~!PGGGY^                               .5PGGG5?.^PGGP5YPPGPY~. YPGJ.                                        
^PPPPPP?                                             JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                       .?5PGGPP!    :PGGGGPJ~!PP5^^JPG5:..^55PPP5J^.                        .:^!?5PGGGGGGGGGPJ7?PPGGGG5J.                                    :5PGGGGGGGGP~~~PGGGGGPJ7.   .YGGGY^                               ~PPGPP!: ^555PGGGGP~.   5PP~                                         
^PPPPPP?                                             JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                       ~YGGGPY~.    :PGGPY~. .PPP!:^!PPYY5P5J!!?PG57.              .:!JJ7!7?5PPGGGGGGGGGGGGPJ. ~PPGGGPJ:                                   .7YGGGGGGGGGGP~^^5GGG5J~       ?GGGY^                             :!5GPGG5.  :^:.!?PGG5.  .^PPJ.                                         
^PPPPPP?                                             JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                      .J5GGGY!      :PGG7.   :PP5:.!JPPJ?!^.   .5GGY~              7JGGGGGGGGGGGP5Y?7YPGGGG57 .JGGGPP!:                                   7YPGGGGGGGGGGGP!: ^JYY^         JGPGY^                          .^J5PGGPPGJ         ?PGP?~~?P5?:                                          
^PPPPPP?                                             JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                      !PPGPG7:      :PGP~    .5PGY?77~:         JGG5J.             !JGGGGGGPYJ7~^.   ~PPGGGP5?JPGGG5?.                                   .5GPGGGGPP??5PGP7:  ...         .5GPGY^                        .:JPGGGGGGGGJ         .^YPGPPGG!:                                           
^PPPPPP?                                             JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                    .:PGGGGP:.  .^?7JPPP~     :~7.     :^!75Y?. ?GG5?.              ^YPG5J~^         :JY55PGGGGGGGGJ~                                    .PGGGGP5!: .YPGP!:              .5GPGY!                      ~J5PGGGP5?5PGGJ           .~PGGGG!:                                           
^PPPPPP?                                             YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                    .~PPGGG?     .~5PGPG~        ..^~?Y5Y7YPJ~..5GGJ^                .~!.             ...:7GGGGGGGGP5J7~.                                .YPGPJ!.   .?5GP!:              .5GGG5J.                   :!PGGGPPJ!. 7YGGJ            :PGGGGP5?:                                         
^PPPPPP?                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~YPPPPP5.                    :7PGGP5~       ~JGPG! .:^^~!?JJJJ7!:. .:. .^PG57.                                   .!YGGGGGGGGGGGGP57~:                              ^7J!.      !JGP!:              :5GGG5J.                   ~JGGGGP5~.  7YGGJ           ~JGGPPGGGGY~:.                                      
^PPPPPP?                                                                                       ?PPPPP5.                    .^PGP5~.        .5GG7 7YGP5J7:.          .!JGGJ^                               ..~7J5GGGGGG5JJJ5PGGGGGPP?^.                                      ^7GP7:             .^5GGG5J.                   ^7GGGGGG5Y??5PGGJ    ..   .!5G5J~!7PGGGG5Y!^.                                   
^PPPPPP?                                                                                       ?PPPPP5.                      ?GJ!           !YG7 ~75?:.       !?J?JY5PPPP!:                       .7J????JY5PGGGGGGG5Y:   .^?YPGGGGGP5J~.                                   .^PG7:               ?GPG5J.                    .7JYYYYY5PGGGGGY.  :YJ^:.?PGP!.   J5GGGGGPPYJ!~...                             
^PPPPPP?                                                                                       ?PPPPP5.                      :~.             .Y~   .          ^75PGGGGGP5:.                       .JPPGGGGGGGGGGGG5J:.       .^755PGGGGPY.                                   .J5^.               ^PPG5J.                           ..^JGPGG5.  :PGP55PP5?     .^J5GGGGGGGGPP5YYY!^                         
^PPPPPP?                                                                                       ?PPPPP5.                                                          .?YPGGY7                           .:^~!???JYJJ7~.              .:~?J5PP!:                                                      .75G5J.                               7YGGP^.  J5GGG?^.         .!?5PPGGGGGGGGGGG7^                       
^PPPPPP?                                                                                       ?PPPPP5.                                                            .^?Y!.                                    .                        .:^..                                                       .!Y5J.                                ^?PP^.  :^7!~.              .::!!777777777^:                       
^PPPPPP?                                                                                       ?PPPPP5.                                                               .                                                                                                                            .^5J.                                  ^^                                                               
^PPPPPP?                                                                                       ?PPPPP5.                                                                                                                                                                                              ~~                                                                                                    
^PPPPPP?                                                                                       JPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPPJ                                                                                     .?PPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPP5:                                                                                   :YPPPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPPP?                                                                                 .7PPPPPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPPPP7                                                                              :?PPPPPPPPPPP5.                                                                                                                                                                                                                                                                                                    
^PPPPPPPPPJ:                                                                         :!YPPPPPPPPPPPPP5.                 ~?J????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????7:                      
^PPPPPPPPPPPY!^:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::^~7J5PPPPPPPPPPPPPPPP5.                 75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5~.                     
^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                 ^7?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????7:                      
^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.                                                                                                                                                                                                                                                                                                    
^555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555PY.                                                                                                                                                                                                                                                                                                    
....................................................................................................                                                                                                                                                                                                                                                                                                      
																																																																																														
																																																																																														
																																																																																														
																																																																																														
:~~^^^^^^^^^^~~^~:  .^^^^^.       :^^^^^       .^^^^^~~~~~~^^^:..         .^^^^^:         ^^^         .^^^^.  ..:^!~:          .^^^^^:         ^^^.                :~~~~^^^^^^^~~~~~.  :^^^^~~~~~~~~~~~.        .:^~~~~^^^:      :^^^^:       .^^^^^       :^^^^^.        :^^.       :^^~^.  ..^~~:.        .^^^^^            .^^^~:  ..:^!^.             .:^~~~~~~^:    :^^^^:      .^^^^^.        
:^^^^?GGGGGP?!~^^.  YGGGGP.      ^PGGGG?       ?GGGGG?~!!~75GGGGPJ.       JGGGGGG!       !GGY       ~YPGGP~ :7J5GGGGG5~        JGGGGGP!       7GGY.                .^^^^?GGGGGP?!~~^. ^PGGGGJ^^^^^^^^^:    .^7YPGPJ!~!JGGG?     ^PGGGG~      .5GGGG7      :PGGGGGY.      ^PG5.    .!5GGGY:.!JYPGGGGP?.      YGGGG7          :JPGGP! :?J5GGGGPY:      .~?YPP5?!~^^~!7?.   JGGGG?     :5GGGG?         
     JGGGGP:       7GGGGP^      :PGGGG5.      ^PGGGG7      .YGGGGG!      !GGPPGGGG7     ^PG5:     ^YGGGGJ.      !PGGGGP^      !GGPPGGGG!     ~PGP:                      JGGGG5:      .YGGGGJ             .?PGGG5~      JGP:    .YGGGG?       7GGGGY.     .YGPPGGGG5.    .5GP^    ^5GGGP!      .YGGGGG?     !GGGG5.        .JGGGGJ.     .!PGGGGP.   ^YPGGP7:              ?GGGP~    ^5GGGG7          
    !GGGGG!       ^PGGGG?      ~PGGGGP~      .5GGGG5.     .!PGP5?^      :PG5.:5GGGGJ.  .5GG~     ^PGGGG7         YGGGGP^     :PG5.^PGGGG?.  .5GP~                      ~GGGGG~       7GGGGG?^^^^^^^^:   :5GGGP7        ^?~     !GGGGP7^^^^^ :PGGGP~      7GG7.?GGGG5:   JGG7    !GGGGP^        ^PGGGG?    .5GGGP~        .5GGGGJ        .5GGGG5.  ?GGGG5:   .:.......    ?GGGP~   !PGGGG7           
   :5GGGGY.      .5GGGGY.     7GGGGGGJ       7GGGGP~.~!7?YPJ^..        .YGP^  :5GGGG5^.JGG?      YGGGGY.        :5GGGP!     .YGP^  :5GGGG5^.JGG?                      .5GGGGJ       ^PGGGGG5?!!!!!!!^   JGGGGJ                :PGGGGG5J7!!~.JGGGGJ      ^PGJ   7GGGGP!.7GGY.   .5GGGG7         ?GGGGY.    ?GGGGJ         !GGGG5.        ^PGGGP~  ~GGGGP:    ^!YGGGGP^    JGGGG57!YGGGGP~            
   ?GGGGP^       !GGGGG7   .!Y?5GGGGP:      :PGGGGJ .!YGGGG57.         7GG!    .YGGGGPPGG5.      ?GGGGJ        :5GGP?:      ?GG!    :5GGGGGPGG5.                      ?GGGGP:      .YGGGG5:             ?GGGG?                ?GGGGP7.     ~PGGGP:     .5G5.    7GGGGGPGGP^     YGGGG!        7GGG5!     ^PGGGP.         ~GGGG5.       ^5GGP7.   :PGGG5.      !GGGG?     .!JJJ7~7PGGGP^             
  ~PGGGG7        7GGGGGPJJY5?.:PGGGG7       JGGGGP.    ^5GGGGP!..^.   ~GGJ      .?GGGGGGP^       .?PGGG7.    ^JGPY7.       ~GG?      .JGGGGGGP^                      ^GGGGG7       7GGGGG~              .YGGGP!.    .~Y57.   ~GGGGG!      .5GGGG?      ?GP~      ~PGGGGGG7      .YGGGP^    .~5GPJ^      .YGGGGP^          !PGGG?.    :?GPY!.      ^5GGGJ.   .~PGGGP:           ^5GGG5:              
 .YP555Y.         !5PPPP5J~.  ?YYYYJ.      ^55555!      .?PGGGGPJ!   .YPY.        !5555P7          .~?Y55JJ???!^.         .YPY.        75555P7                       JP555J.      :555555YJJJJJJJJJ^      :!J5P5YJJYYJ!:    .J5555?       !P555Y.     ^5P7        :Y5555J.        :!JY5Y?7???!:         ~5555555YYYYY5!    .~?Y55J?7??!^.           :!?YY?7?Y5YJ7!:          ^YGGGP?.               
                     ..                                   .....                                                                                                                                                ....                                                                                                                                                    .!7?JY55J!:                  
                                                                                                                                                                                                                                                                                                                                                                         ...                        



'''



def version():
	global VERSION
	return VERSION