[tool.poetry]
name = "giving"
version = "0.3.10"
description = "Reactive logging"
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/breuleux/giving"

[tool.poetry.dependencies]
python = "^3.6"
Rx = "^3.2.0"
varname = "^0.8.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", python = "^3.7"}
breakword = {version = "^0.3.1", python = "^3.7"}
isort = {version = "^5.9.3", python = "^3.7"}
flake8 = {version = "^3.9.2", python = "^3.7"}
pytest = "^6.2.4"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = "giving"
known_third_party = ""
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
skip = 'examples/mnist/main.py'

[tool.black]
exclude = 'examples/mnist/main.py'
