
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-19T11:44:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e345d4deed6cdeeb5c1a3c12fd802a916f5f69cc",
 "version": "1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
