# Generated by Django 3.2.7 on 2022-03-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_core', '0002_category_filemodeltemplate_modeltemplate_pathmodeltemplate_stringmodeltemplate'),
        ('simpel_sales', '0002_salessetting_salesquotation_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='salesorder_template',
            field=models.ForeignKey(blank=True, help_text='Custom Quotation template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simpel_core.filemodeltemplate', verbose_name='Quotation Template'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesorder_expiration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Expiration'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesorder_signer_eid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Signer EID'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesorder_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Signer'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesorder_signer_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Signer Position'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesquotation_expiration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quotation Expiration'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesquotation_signer_eid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quotation Signer EID'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesquotation_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quotation Signer'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='salesquotation_signer_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quotation Signer Position'),
        ),
    ]
