
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T13:24:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f038dc3a52cfb24bb93eee02beeac815c61b9427",
 "version": "0.5.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
