
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T22:14:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b76c9da44c7a1c608fdea59843b753f871a3b59",
 "version": "0.0.70.post0.dev73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
