
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T00:31:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac8f666d0ea14055dc811f5ab724414a18bcaafb",
 "version": "0.0.70.post0.dev55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
