# Generated by Django 3.2.7 on 2022-03-17 01:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpel_feedbacks', '0004_auto_20220316_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='userflag',
            options={'verbose_name': 'Flag', 'verbose_name_plural': 'Flags'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterIndexTogether(
            name='userfeedback',
            index_together={('feedback_object_id', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='userflag',
            index_together={('flagged_object_id', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='userrating',
            index_together={('rated_object_id', 'user')},
        ),
    ]
