# Generated by Django 3.1.13 on 2021-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhro_diva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empfaenger',
            name='required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
