[tool.poetry]
name = "revpayment"
version = "3.1.3"
description = ""
authors = ["Chien <a0186163@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
Django = "^3.1.7"
djangorestframework = "^3.12.4"
requests = "^2.25.1"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-django = "^4.1.0"
black = "^20.8b1"
isort = "^5.8.0"
autoflake = "^1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
