# Generated by Django 3.2.7 on 2022-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_core', '0002_category_filemodeltemplate_modeltemplate_pathmodeltemplate_stringmodeltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='phone',
            field=models.CharField(blank=True, help_text='Valid phone with format +62XXXXXXX', max_length=15, null=True, verbose_name='phone'),
        ),
    ]
