
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T17:04:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "34140c28cf29d6893de56735a05f99e78011def7",
 "version": "0.2.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
