
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T19:11:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "76bd313d77ca0927120fb07c6a584ab9f14d2f06",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
