[tool.poetry]
name = "libadvian"
version = "1.1.0"
description = "Small helpers that do not warrant their own library"
authors = ["Eero af Heurlin <eero.afheurlin@advian.fi>"]
homepage = "https://gitlab.com/advian-oss/python-libadvian/"
repository = "https://gitlab.com/advian-oss/python-libadvian/"
license = "MIT"
readme = "README.rst"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  |  __pycache__
)
'''

[tool.pytest.ini_options]
junit_family="xunit2"
addopts="--cov=libadvian --cov-fail-under=65 --cov-branch"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable=["fixme", "W1202", "C0330", "C0209"]

[tool.coverage.run]
omit = ["tests/*"]
branch = true

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"  # fresh black requires at least 3.6.2 so we can't use ^3.6

[tool.poetry.dev-dependencies]
pytest = [
    { version = "^7.1", python="^3.7" },
    { version = "^6.2", python="~3.6" }
]
coverage = [
    { version = "^6.3", extras = ["toml"], python="^3.7" },
    { version = "^5.4", extras = ["toml"], python="~3.6" }
]
pytest-cov = "^3.0"
pylint = "^2.12"
black = "^22.1"
bandit = [
    { version = "^1.7", extras = ["toml"], python="^3.7" },
    { version = "=1.7.1", extras = ["toml"], python="~3.6" }
]
mypy = "^0.941"
pre-commit = "^2.17"
pytest-asyncio = [
    { version="^0.18", python="^3.7" },
    { version="^0.14", python="~3.6" }
]
bump2version = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
