# Generated by Django 2.2.27 on 2022-02-11 14:14

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0031_circle_parentcircle'),
        ('djangoldp_sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='externallink',
            new_name='externalLink',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du produit'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la vente')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='djangoldp_circle.Circle')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
            },
        ),
    ]
