# Generated by Django 2.2.27 on 2022-03-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0006_productstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(blank=True, default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='productstock', to='djangoldp_sales.Product', verbose_name='produits'),
            preserve_default=False,
        ),
    ]
