# Generated by Django 2.2.27 on 2022-03-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
