# Generated by Django 2.2.27 on 2022-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0012_auto_20220308_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderquantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité commandée'),
        ),
    ]
