# Generated by Django 2.2.27 on 2022-03-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0014_auto_20220308_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='djangoldp_sales.Product', verbose_name='produits'),
        ),
    ]
