# Generated by Django 2.2.27 on 2022-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0015_auto_20220308_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('validated', 'Payée'), ('cancelled', 'Annulée')], max_length=50, null=True, verbose_name='Status de la commande'),
        ),
    ]
