# Generated by Django 2.2.27 on 2022-03-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0017_order_transactiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderquantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='order',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstock', to='djangoldp_sales.Order', verbose_name='commande'),
        ),
    ]
