# Generated by Django 2.2.27 on 2022-03-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0019_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleorder', to='djangoldp_sales.Sale', verbose_name='vente'),
        ),
    ]
