[tool.poetry]
name = "felixlib"
version = "0.0.27"
description = "felixlib"
authors = ["spectereye <spectereye@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7,!=3.7.6"  # python 3.7.6 doesn't work with pywinauto

[tool.poetry.dev-dependencies]
# this project used as library, place all dependencies in dev below,
# so other project using it can select dependencies needed only
numpy = "^1.18.5"
flask = "^1.1"
flask_wtf = "^0.14.3"
wtforms = "^2.2"
psutil = "^5.6"
pywebview = "^3.1"
pywinauto = ">=0.6.0"
xlwings = "^0.16.0"
colorama = "^0.4.1"
pywin32 = "^225"
send2trash = "^1.5"
pysimplegui = "^4.14"
docstring-parser = "^0.6.1"
autopep8 = "^1.5.7"
PySnooper = "^0.5.0"
fire = "^0.3.1"
pytest = "^6.2.1"
pywin32-ctypes = "^0.2.0"
fastapi = "^0.75.0"

# dependencies for build
cython = "^0.29.14"
pyinstaller = {path = "../pyinstaller"}
dearpygui = "^0.8.64"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
