
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T19:46:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2ab92eb3cfdfa1a5c0a27f6d0bd1c3f204992b3",
 "version": "0.0.70.post0.dev69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
