[tool.commitizen]
name = "cz_commitizen_oca"
version = "0.1.3"
version_files = [
    "src/__version__.py",
    "pyproject.toml:version"
]
bump_message = "[REL]: version $current_version → $new_version"
