# Generated by Django 2.2.27 on 2022-03-03 19:31

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0005_auto_20220215_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('stockMovement', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('transactionType', models.CharField(blank=True, choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10, null=True, verbose_name='type de transaction')),
                ('transactionDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ManyToManyField(blank=True, max_length=50, related_name='productstock', to='djangoldp_sales.Product', verbose_name='produits')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
            },
        ),
    ]
