# Generated by Django 2.2.27 on 2022-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0020_order_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='prix total'),
        ),
    ]
