# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_inspection', '0002_inspectiontask_inspectiontaskparameter'),
        ('simpellab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontaskparameter',
            name='analysis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_task_parameters', to='simpellab.analysismethod'),
        ),
        migrations.AddField(
            model_name='inspectiontaskparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_task_parameters', to='simpellab.parameter'),
        ),
        migrations.AddField(
            model_name='inspectiontaskparameter',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='mod_inspection.inspectiontask'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectiontaskparameter',
            unique_together={('task', 'parameter')},
        ),
    ]
