
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T13:42:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d221fce85c1bcc063945a52a96aead350b4e522f",
 "version": "5.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
