# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_laboratorium', '0001_initial'),
        ('simpel_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoriumTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_projects.task')),
            ],
            options={
                'verbose_name': 'Laboratorium Task',
                'verbose_name_plural': 'Laboratorium Tasks',
                'db_table': 'simpel_laboratorium_task',
                'ordering': ('position',),
                'permissions': (('import_laboratoriumtask', 'Can import Laboratorium Task'), ('export_laboratoriumtask', 'Can export Laboratorium Task')),
            },
            bases=('simpel_projects.task',),
        ),
        migrations.CreateModel(
            name='LaboratoriumTaskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('position', models.IntegerField(default=0, help_text='Enable sortable position', verbose_name='position')),
            ],
            options={
                'verbose_name': 'Laboratorium Task Parameter',
                'verbose_name_plural': 'Laboratorium Task Parameters',
                'db_table': 'simpel_laboratorium_task_parameter',
                'ordering': ('position',),
                'permissions': (('import_laboratoriumtaskparameter', 'Can import Laboratorium Task Parameter'), ('export_laboratoriumtaskparameter', 'Can export Laboratorium Task Parameter')),
            },
        ),
    ]
