# Generated by Django 2.2.27 on 2022-02-14 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoldp_sales', '0002_auto_20220211_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control'], 'ordering': ['startDate']},
        ),
        migrations.AddField(
            model_name='product',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix en centimes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdSales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(blank=True, max_length=50, related_name='sale', to='djangoldp_sales.Product', verbose_name='produits'),
        ),
    ]
