# Generated by Django 2.2.27 on 2022-03-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0011_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='removestock',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='djangoldp_sales.Product', verbose_name='produits'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='order',
            field=models.ForeignKey(blank=True, default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='orderstock', to='djangoldp_sales.Order', verbose_name='commande'),
            preserve_default=False,
        ),
    ]
