# Generated by Django 2.2.27 on 2022-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_sales', '0016_order_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
