[tool.poetry]
name = "envcrypt"
version = "0.1.0"
description = "Encrypt and decrypt environment variable files."
authors = ["Dan Kelleher <dan@danklabs.org>"]

[tool.poetry.dependencies]
python = "^3.9"
pycrypto = "^2.6.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
