name: Tests

# Test on all pushes, except when the push is literally just a tag (because we
# tag automatically via CI, and therefore there's no extra code in that push).
on:
  push:
    tags-ignore:
      - 'v*'
  pull_request:


jobs:
  tests:
    env:
      ENV_NAME: tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # macos-latest doesn't work for polychord yet...
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: set PY
        run: echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_ENV
      # - name: Setup MPI
      #   uses: mpi4py/setup-mpi@v1
      - name: Setup Environment
        run: |
          pip install -U coverage
          pip install .[dev]
      - name: Setup polychord
        run: |
          git clone https://github.com/PolyChord/PolyChordLite
          cd PolyChordLite
          python setup.py --no-mpi install
          cd ..
      - name: Run Tests
        run: |
          python -m pytest --cov-report xml:./coverage.xml
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
