
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T07:19:26+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "96af4fa990866a9202a90aa4022cf33211b13819",
 "version": "0.9.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
