[tool.poetry]
name = "qctrl-toolkit"
version = "0.0.0"
description = "Q-CTRL Python Toolkit"
license = "https://q-ctrl.com/terms"
authors = ["Q-CTRL <support@q-ctrl.com>"]
maintainers = ["Q-CTRL <support@q-ctrl.com>"]
readme = "README.md"
homepage = "https://q-ctrl.com"
repository = ""
documentation = ""
keywords = [
    "black opal",
    "boulder opal",
    "nisq",
    "open controls",
    "q control",
    "q ctrl",
    "q-control",
    "q-ctrl",
    "qcontrol",
    "qctrl",
    "quantum",
    "quantum algorithms",
    "quantum circuits",
    "quantum coding",
    "quantum coding software",
    "quantum computing",
    "quantum control",
    "quantum control software",
    "quantum control theory",
    "quantum engineering",
    "quantum error correction",
    "quantum firmware",
    "quantum fundamentals",
    "quantum sensing",
    "qubit",
    "qudit"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Distributed Computing"
]
packages = [
    { include = "qctrltoolkit" },
]

[tool.poetry.dependencies]
python = ">=3.6.4, <3.10"
numpy = ">=1.16.2"
toml = "^0.10.0"
python-forge = "^18.6.0"
dataclasses = {version = "*", python = ">=3.6.4,<3.7"}
qctrl-commons = "^15.0.2"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
black = "^20.8b1"
isort = "^5.7.0"
pre-commit = "^2.9.3"
pytest = "^5.0.1"
pytest-cov = "^2.6.1"
pytest-mock = "^1.10.3"
pylint = "^2.12.2"
pylint_runner = "^0.6.0"
sphinx = "^3.2.1"
sphinx-rtd-theme = "^0.4.3"
numpydoc = "^1.1.0"
docutils = "^0.17.1"

[tool.poetry.urls]
LinkedIn = "https://www.linkedin.com/company/q-ctrl/"
Facebook = "https://www.facebook.com/qctrl"
Twitter = "https://twitter.com/qctrlHQ"
YouTube = "https://www.youtube.com/c/qctrl"
GitHub = "https://github.com/qctrl"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.pytest_cache
    | \.github
    | docs
  )/
)
'''

[tool.isort]
profile = "black"
force_grid_wrap = "2"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-m 'not slow'"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
