# Generated by Django 3.1.6 on 2021-05-29 01:37

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('custom', '0002_configuration_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='offer_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Offer image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='no_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_image', to=settings.FILER_IMAGE_MODEL, verbose_name='No image'),
        ),
    ]
