# Generated by Django 3.1.6 on 2021-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_auto_20210529_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='color_2',
            field=models.CharField(blank=True, help_text='CSS second color of the brand.', max_length=50, null=True, verbose_name='Second accent color'),
        ),
    ]
