# Generated by Django 3.1.6 on 2021-06-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('custom', '0004_auto_20210602_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='header_hints_bottom_1_url',
            field=models.URLField(blank=True, null=True, verbose_name='Header hints block bottom left url'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='header_hints_bottom_2_url',
            field=models.URLField(blank=True, null=True, verbose_name='Header hints block bottom right url'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='header_hints_top_1_responsive',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_hints_top_1_responsive', to=settings.FILER_IMAGE_MODEL, verbose_name='Header hints block top image responsive'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='header_hints_top_1_url',
            field=models.URLField(blank=True, null=True, verbose_name='Header hints block top url'),
        ),
    ]
