# Generated by Django 3.1.6 on 2021-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_auto_20210607_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='company_city',
            field=models.CharField(default='City', max_length=255, verbose_name='Second line of address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_postcode',
            field=models.CharField(default='12345', max_length=64, verbose_name='Post/Zip-code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_short_name',
            field=models.CharField(default='Company', help_text='This is the short company name (eg. Company)', max_length=150, verbose_name='Short company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_street',
            field=models.CharField(default='Straße #', max_length=255, verbose_name='First line of address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_support_email',
            field=models.EmailField(default='info@company.de', help_text='The email of the support for the shop customers', max_length=254, verbose_name='Company contact information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_support_phone',
            field=models.CharField(default='0', help_text='The number of the support for the shop customers', max_length=255, verbose_name='Company support email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='color_2',
            field=models.CharField(default='black', help_text='CSS second color of the brand.', max_length=50, verbose_name='Second accent color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='home_bottom_text',
            field=models.TextField(blank=True, help_text='Text on the bottom of the start page, sometimes used for seo', null=True, verbose_name='content'),
        ),
    ]
