# Generated by Django 3.1.6 on 2021-06-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('custom', '0006_auto_20210609_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='company_city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='company_support_email',
            field=models.EmailField(help_text='The email of the support for the shop customers', max_length=254, verbose_name='Company support email'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='company_support_phone',
            field=models.CharField(help_text='The number of the support for the shop customers', max_length=255, verbose_name='Company support phone'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo_square',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_image_square', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo square'),
        ),
    ]
