# Generated by Django 3.1.6 on 2021-06-25 09:40

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('custom', '0007_auto_20210610_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo_square',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_image_square', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo square'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='no_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_image', to=settings.FILER_IMAGE_MODEL, verbose_name='No image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='offer_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Offer image'),
        ),
    ]
