# Generated by Django 3.2.5 on 2021-08-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0003_auto_20181115_1953'),
        ('custom', '0009_auto_20210817_2151'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tagvalue',
            name='custom_tagvalue_tag_values',
        ),
        migrations.AddField(
            model_name='tag',
            name='wishlist_lines',
            field=models.ManyToManyField(related_name='tags', through='custom.TagValue', to='wishlists.Line'),
        ),
        migrations.AddField(
            model_name='tag',
            name='wishlists',
            field=models.ManyToManyField(related_name='tags', through='custom.TagValue', to='wishlists.WishList'),
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to='wishlists.wishlist'),
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='wishlist_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to='wishlists.line'),
        ),
        migrations.AlterField(
            model_name='tagvalue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to=settings.AUTH_USER_MODEL),
        ),
    ]
