# Generated by Django 3.2.5 on 2021-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='google_site_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
