# Generated by Django 3.2.9 on 2021-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0012_configuration_google_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='basket_sumup_with_deposit',
            field=models.BooleanField(default=True, help_text='In Warenkorb und Checkout wird der Preis nicht summiert angezeigt.', verbose_name='Warenkorb Summe mit Pfand'),
        ),
    ]
