# Generated by Django 3.2.10 on 2022-01-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0014_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='email_host',
            field=models.CharField(default='NEED INPUT!!!', help_text='Für den Login beim Email Provider', max_length=100, verbose_name='Email Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_name',
            field=models.CharField(default='NEED INPUT!!!', help_text='z.B. Company.de wird zu "Company.de <info@company.de>"', max_length=100, verbose_name='Email Absender Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_password',
            field=models.CharField(default='NEED INPUT!!!', help_text='Für den Login beim Email Provider', max_length=100, verbose_name='Email Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_port',
            field=models.PositiveSmallIntegerField(default=587, help_text='Für den Login beim Email Provider', verbose_name='Email Port'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_reply_to',
            field=models.EmailField(blank=True, help_text='Wird in der Email als Antwortadresse angegeben', max_length=254, null=True, verbose_name='Email Antwort Adresse'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_sender',
            field=models.EmailField(default=models.CharField(help_text='Für den Login beim Email Provider', max_length=100, verbose_name='Email Benutzername'), help_text='z.B. info@company.de wird zu "Company.de <info@company.de>"', max_length=254, verbose_name='Email Absender Adresse'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Für den Login beim Email Provider', verbose_name='TLS verwenden'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_user',
            field=models.CharField(default='NEED INPUT!!!', help_text='Für den Login beim Email Provider', max_length=100, verbose_name='Email Benutzername'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_all_products',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, werden alle Produkte angezeigt statt der abonnierten', verbose_name='Alle Produkte'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociallinks', to='custom.configuration'),
        ),
    ]
