[tool.poetry]
name = "fakts"
version = "0.1.47"
description = "asynchronous configuration protocol for dynamic client-server relations"
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
readme = "README.md"
packages = [{include = "fakts"}]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"
PyYAML = ">= 5.2"
QtPy = "^1.11.2"
koil = "^0.1.96"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.5"
black = "^21.12b0"
pytest-cov = "^3.0.0"
pytest-qt = "^4.0.2"
PyQt5 = "^5.15.6"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
