# Generated by Django 3.2.7 on 2022-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_invoices', '0002_invoicesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
