
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T22:13:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "845e80f3c1920f29124f3fa95537c43506725dbe",
 "version": "0.0.70.post0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
