language: python
matrix:
  include:
  # command to install dependencies
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-6
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-6"
      - os: linux
        python: 2.7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-7
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-7"
      - os: linux
        python: 3.4
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-7
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-7"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-7
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-7"
      - os: linux
        python: 2.7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.4
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 2.7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
      - os: linux
        python: 3.4
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
install: 
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - python setup.py install
# command to run tests
script: 
  - coverage run --source=gfort2py setup.py test
env: 
  TRAVIS=1
after_success:
    coveralls
cache: 
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
