name: CI

on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        toxenv: [black, flake8, mypy]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    - name: Run tox ${{ matrix.toxenv }}
      run: tox -e ${{ matrix.toxenv }}

  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
        include:
        - os: macos-latest
          python-version: 3.7
        - os: ubuntu-20.04
          python-version: 3.7
          with-isal: true
        - os: windows-latest
          python-version: 3.7
    steps:
    - name: Install pigz and pbzip2 MacOS
      if: runner.os == 'macOS'
      run: brew install pigz pbzip2
    - name: Install pigz and pbzip2 Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install pigz pbzip2
    - name: Install isal
      if: matrix.with-isal && runner.os == 'Linux'
      run: sudo apt-get install isal libisal-dev
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    - name: Test
      run: tox -e py
      if: matrix.with-isal == null
    - name: Test with isal
      run: tox -e isal
      if: matrix.with-isal
    - name: Upload coverage report
      uses: codecov/codecov-action@v1

  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # required for setuptools_scm
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Make distributions
      run: |
        python -m pip install build
        python -m build
        ls -l dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
