# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab', '0001_initial'),
        ('mod_laboratorium', '0002_laboratoriumtask_laboratoriumtaskparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoriumtaskparameter',
            name='analysis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorium_task_parameters', to='simpellab.analysismethod'),
        ),
        migrations.AddField(
            model_name='laboratoriumtaskparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorium_task_parameters', to='simpellab.parameter'),
        ),
        migrations.AddField(
            model_name='laboratoriumtaskparameter',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='mod_laboratorium.laboratoriumtask'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratoriumtaskparameter',
            unique_together={('task', 'parameter')},
        ),
    ]
