# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpel_products', '0002_alter_product_is_sellable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationService',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_products.product')),
            ],
            options={
                'verbose_name': 'Product Certification',
                'verbose_name_plural': 'Product Certifications',
                'db_table': 'simpel_certification_service',
                'permissions': (('export_certificationservice', 'Can export Certification Service'), ('import_certificationservice', 'Can import Certification Service')),
            },
            bases=('simpel_products.product',),
        ),
    ]
