
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-19T16:32:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9023e2b3d3e804c5672c0ae6c160f1d74798a373",
 "version": "2.5.3.dev20220321"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
