
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-22T12:05:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a81dddd6161f836d70e68bafdc5244c19c8ccae",
 "version": "1.16.0.post.dev293"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
