# Generated by Django 3.0.10 on 2021-02-07 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BooleanField(default=True)),
                ('sepa', models.BooleanField(default=True)),
                ('transfer', models.BooleanField(default=False)),
                ('account', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpaymentselection_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpaymentselection_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_selection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment selection for User',
            },
        ),
    ]
