# Generated by Django 3.1.6 on 2021-02-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_userpaymentselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpaymentselection',
            options={'verbose_name': 'Payment selection for User', 'verbose_name_plural': 'Payment selections for User'},
        ),
    ]
