# Generated by Django 3.0.10 on 2021-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210208_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentselection',
            name='account',
            field=models.BooleanField(default=None, verbose_name='Auf Rechnung'),
        ),
        migrations.AlterField(
            model_name='userpaymentselection',
            name='cash',
            field=models.BooleanField(default=None, verbose_name='Bar/EC'),
        ),
        migrations.AlterField(
            model_name='userpaymentselection',
            name='reason',
            field=models.TextField(verbose_name='Grund'),
        ),
        migrations.AlterField(
            model_name='userpaymentselection',
            name='sepa',
            field=models.BooleanField(default=None, verbose_name='Sepa'),
        ),
        migrations.AlterField(
            model_name='userpaymentselection',
            name='transfer',
            field=models.BooleanField(default=None, verbose_name='Überweisung'),
        ),
    ]
