# Generated by Django 3.1.6 on 2021-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210215_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentselection',
            name='transfer',
            field=models.BooleanField(default=None, verbose_name='Vorkasse'),
        ),
    ]
