[tool.poetry]
name = "paradigm-panes"
version = "0.2.1"
description = "Paradigm panes meant to provide layout specification to be reused elsewhere."
authors = ["Uladzimir Bondarau <bondarau@ualberta.ca>"] # TODO
license = "Apache License v2.0"
readme = "README.md"
homepage = "https://github.com/UAlbertaALTLab/paradigm-panes"
repository = "https://github.com/UAlbertaALTLab/paradigm-panes"
keywords = ["paradigm", "panes"]
classifiers = [
    # "Framework :: Flake8",
    # "Topic :: Software Development :: Documentation",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"
more-itertools = "~=8.7.0"
hfst-optimized-lookup = "~=0.0.13"
typing-extensions = "~=3.7"
requests = "*"
pathlib = "*"

# extra
# sudo apt-get install -y hfst

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
