
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T11:47:43+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "654bea650c88d1f008a20c48f769894c6f4eff2d",
 "version": "1.0.8rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
