# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_calibration', '0001_initial'),
        ('simpel_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpel_projects.task')),
            ],
            options={
                'verbose_name': 'Calibration Task',
                'verbose_name_plural': 'Calibration Task',
                'db_table': 'simpel_calibration_task',
            },
            bases=('simpel_projects.task',),
        ),
    ]
