# Generated by Django 3.2.7 on 2022-02-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_calibration', '0002_calibrationtask'),
        ('simpellab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationservice',
            name='analysis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibrations', to='simpellab.analysismethod'),
        ),
    ]
