# Generated by Django 3.2.7 on 2022-03-16 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpel_feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='UserComment',
        ),
    ]
