# Generated by Django 3.2.7 on 2022-03-16 08:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpel_feedbacks', '0002_rename_feedback_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rated_object_id', models.IntegerField(help_text='Rated object primary key.')),
                ('value', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rated_object_type', models.ForeignKey(help_text='Rated object type', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(limit_choices_to={'is_partial': True}, on_delete=django.db.models.deletion.CASCADE, related_name='rated_objects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('flagged_object_id', models.IntegerField(help_text='Flagged object primary key.')),
                ('flagged_object_type', models.ForeignKey(help_text='Flagged object type', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(limit_choices_to={'is_partial': True}, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
