
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T11:27:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "13f0f8ba6d292f651e8bbe26210e2a8fd796af42",
 "version": "1.16.0.post.dev289"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
