default_language_version:
    python: python3

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
    -   id: requirements-txt-fixer
        language_version: python3
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        language_version: python3
        args: ["--target-version", "py37"]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3
        args: ['--config=setup.cfg']
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        language_version: python3
        args: ['--profile', 'black']
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        language_version: python3
        args: ['--convention=numpy', '--match="(?!test_).*\.py"']
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#    -   id: mypy
#        additional_dependencies: [
#            # Type stubs
#            types-python-dateutil,
#            types-pkg_resources,
#            types-PyYAML,
#            types-pytz,
#            # Dependencies that are typed
#            numpy,
#            xarray,
#            xclim,
#            typing-extensions==3.10.0.0,
#          ]

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
