# Generated by Django 3.2.12 on 2022-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohotkey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotkey',
            name='help_text',
            field=models.TextField(blank=True, help_text='热键说明', null=True),
        ),
    ]
