# Generated by Django 3.2.12 on 2022-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohotkey', '0002_alter_hotkey_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='help_text',
            field=models.TextField(blank=True, help_text='热键说明', null=True),
        ),
    ]
