
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T12:51:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9479545de1d6f6eecb7b9fa90df6435781f01eb8",
 "version": "2.0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
