# Generated by Django 3.2.7 on 2022-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_sales', '0006_salesorder_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
