# Generated by Django 3.2.11 on 2022-02-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubscription',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsubscription',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Verbundener Shop', 'verbose_name_plural': 'Verbundene Shops'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='users',
        ),
        migrations.AddField(
            model_name='shop',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, wird auf diesem Shop kein sync durchgeführt', verbose_name='Aktiviert'),
        ),
        migrations.AddField(
            model_name='shop',
            name='master',
            field=models.BooleanField(default=False, help_text='Dies ist die Verbindung zur Master Api', unique=True, verbose_name='Master'),
        ),
        migrations.DeleteModel(
            name='Change',
        ),
        migrations.DeleteModel(
            name='ProductSubscription',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
