
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T19:00:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c3be236a95ce567ae5f7ff670472aa08ffeb0cd",
 "version": "v0.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
