# Configuration file for GitLab CI
# Reference docs at https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
  - build
  - test
  - deploy


# Global variables, don't nest inside this scope -> breaks on Windows runner
variables:
  CACHE_DIR: ${CI_PROJECT_DIR}/.cache
  # Move pip's and conda's cache directory inside project directory.
  # Don't use "pip install ." together with a local cache directory. Pip will
  # copy the entire source directory (cache included) during the build and
  # installation process. This can be avoided by either using the "--editable"
  # flag or by installing distribution archives pre-build with "sdist" or
  # "bdist_wheel".
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache
  CONDA_PKGS_DIRS: ${CI_PROJECT_DIR}/.cache


cache:
  # Use separate cache for each job
  key: ${CI_JOB_NAME}
  paths:
    - ${CACHE_DIR}


# Template for linux jobs
.linux:
  # Set default python version https://hub.docker.com/_/python.
  # Override on a per job basis when another version is needed.
  image: python:3.10
  before_script:
    - ls -Alh --group-directories-first
    - python -VV
    - python -m pip install --upgrade pip wheel


# Check code style and lint
black flake8:
  extends: .linux
  stage: test
  needs: []
  script:
    - pip install --retries 3 black>=20.8b1 flake8
    - black --check --diff doc src test setup.py
    - flake8 --show-source doc src test setup.py


# Build distribution archives & HTML documentation
sdist wheel sphinx:
  extends: .linux
  stage: build
  script:
    - python setup.py sdist bdist_wheel
    - pip install --retries 3 sphinx~=2.4 numpydoc==0.9.2 sphinx-rtd-theme==0.4.3
        docutils==0.16 jinja2==3.0.3 dist/ptvpy-*.whl
    - python doc/build_doc.py --show-private --sphinx="-n -v -W" build/
  artifacts:
    paths:
      - dist
      - build
    expire_in: 10 days


# Template for test jobs
.test:
  stage: test
  variables:
    # Ignore errors raised due to running doctests against an installed version
    # See https://github.com/pytest-dev/pytest/issues/2042#issuecomment-429289164
    PY_IGNORE_IMPORTMISMATCH: 1
  artifacts:
    reports:
      junit: pytest-report.xml
    expire_in: 30 days


# End of support 2026-10
py3_10 pytest:
  extends:
    - .linux
    - .test
  script:
    - pip install --retries 3 pytest dist/ptvpy-*.whl
    - ptvpy -h
    - pytest -vv --showlocals --doctest-modules --junitxml=pytest-report.xml


# End of support 2025-10
py3_9 pytest cov:
  extends:
    - .linux
    - .test
  image: python:3.9
  variables:
    # Disable to make jitted function visible in coverage report
    NUMBA_DISABLE_JIT: 1
  script:
    - pip install --retries 3 pytest-cov dist/ptvpy-*.whl
    - ptvpy -h
    - pytest -vv --showlocals --doctest-modules --cov --junitxml=pytest-report.xml


# End of support 2024-10
py3_8 pytest:
  extends:
    - .linux
    - .test
  image: python:3.8
  script:
    - pip install --retries 3 pytest dist/ptvpy-*.whl
    - ptvpy -h
    - pytest -vv --showlocals --doctest-modules --junitxml=pytest-report.xml


# End of support 2023-06-27
py3_7 pytest:
  extends:
    - .linux
    - .test
  image: python:3.7
  script:
    - pip install --retries 3 pytest dist/ptvpy-*.whl
    - ptvpy -h
    - pytest -vv --showlocals --doctest-modules --junitxml=pytest-report.xml


# See https://docs.gitlab.com/ee/user/gitlab_com/#windows-shared-runners-beta
windows py3_10 pytest:
  extends: .test
  tags:
    - windows
  before_script:
    - dir
    - choco config set cacheLocation $env:CACHE_DIR
    - choco install --no-progress -y python --version=3.10.2
    # Make sure Python is in the PATH, Chocolateys's recommended command
    # "refreshenv" is not available at this stage
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";"
        + [System.Environment]::GetEnvironmentVariable("Path","User")
    - python -VV
    - python -m pip install --upgrade pip
  script:
    - pip install --retries 3 ( get-item dist/ptvpy-*.whl ) pytest
    - ptvpy -h
    - pytest -vv --showlocals --junitxml=pytest-report.xml
    # Array representations look differently on Windows, still run doctests but
    # cover exitcode, see https://github.com/numpy/numpy/issues/13468
    - pytest -vv --showlocals --doctest-modules .\src; powershell -c "exit 0"


# Deploy HTML documentation
pages:
  stage: deploy
  # Trigger only for tags matching starting with a "v"
  only:
    - tags
    - /^v.*$/
  except:
    - merge_requests
  script:
    - cp -r build public
  artifacts:
    expire_in: 10 days
    paths:
      - public