
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-21T17:51:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c89226303a951b817a39f5b5ee6fc14635d4233e",
 "version": "2.5.3.dev20220322"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
