
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-23T11:36:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5672841ee2b005f3a1120daf17b5c4e92f05a2b9",
 "version": "0.7.1.post.dev441"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
