
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T13:53:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d44f110700a1ca062744aedcab61531677a054e",
 "version": "0.0.70.post0.dev114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
