[tool.poetry]
name = "rygforms"
version = "0.5.7"
description = "OAuth2 Login for Typeform and Tripetto"
authors = ["Stefano Pigozzi <me@steffo.eu>", "Lorenzo Balugani <lorenzo.balugani@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"
authlib = "^0.15.2"
requests = "^2.25.1"
python-dotenv = "^0.15.0"
click = "^8.0.3"
itsdangerous = "^2.1.2"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
