# Generated by Django 3.2.7 on 2022-03-13 08:51

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('simpel_products', '0002_alter_product_is_sellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_thumbnails', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
