[tool.poetry]
name = "skit-fixdf"
version = "0.1.12"
description = "A library to format datasets so that you don't have to."
authors = ["ltbringer <amresh.venugopal@gmail.com>"]
license = "GPL-3.0-only"
repository = "https://github.com/skit-ai/skit-fixdf"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.3.5"
tqdm = "^4.62.3"
loguru = "^0.5.3"
toml = "^0.10.2"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^21.12b0"
mypy = "^0.931"
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
skit-fixdf = "skit_fixdf.cli:main"
