# Generated by Django 3.1.6 on 2021-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20210604_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sftpcommunication',
            options={'verbose_name': 'SFTP Communication Profile'},
        ),
        migrations.AlterField(
            model_name='sftpcommunication',
            name='sftp_port',
            field=models.PositiveSmallIntegerField(default=22, help_text='Port of the target system to connect to', verbose_name='SFTP port'),
        ),
    ]
