# Generated by Django 3.1.6 on 2021-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20210614_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationeventtype',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'HTML and plain text'), (1, 'HTML'), (2, 'Plain text')], default=0, help_text='Choose Format if matching template exists (only Custom)', verbose_name='E-Mail Format'),
        ),
    ]
