# Generated by Django 3.2.5 on 2021-09-03 20:18

from django.db import migrations, models
from apps.communication.models import CommunicationEventType


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_communicationeventtype_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationeventtype',
            name='event_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'E-Mail geändert'), (2, 'Bestellung'), (3, 'Passwortänderung'), (4, 'Passwortrücksetzung'), (5, 'Produktbenachrichtigung'), (6, 'Registrierung'), (21, 'Bestellungsinformationen mit Bankdaten'), (22, 'Bestellungsinformationen ohne Bankdaten'), (23, 'Maschinenlesbare E-Mail 1'), (24, 'Bestellungsinformationen Überweisung')], null=True, unique=True, verbose_name='Communication event type'),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='email_recipients',
            field=models.ManyToManyField(blank=True, help_text='Empfangen alle Nachrichten dieses Typs.', to='communication.EmailRecipient', verbose_name='E-Mail recipients'),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'E-Mail geändert'), (2, 'Bestellung'), (3, 'Passwortänderung'), (4, 'Passwortrücksetzung'), (5, 'Produktbenachrichtigung'), (6, 'Registrierung'), (21, 'Bestellungsinformationen mit Bankdaten'), (22, 'Bestellungsinformationen ohne Bankdaten'), (23, 'Maschinenlesbare E-Mail 1'), (24, 'Bestellungsinformationen Überweisung')], unique=True, verbose_name='Communication event type'),
        ),
    ]
