# Generated by Django 3.2.9 on 2021-12-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20210903_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationeventtype',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'E-Mail geändert'), (2, 'Bestellung'), (3, 'Passwortänderung'), (4, 'Passwortrücksetzung'), (5, 'Produktbenachrichtigung'), (6, 'Registrierung'), (21, 'Bestellungsinformationen mit Bankdaten'), (22, 'Bestellungsinformationen ohne Bankdaten'), (23, 'Maschinenlesbare E-Mail 1'), (24, 'Bestellungsinformationen Überweisung'), (25, 'Objekte importiert')], unique=True, verbose_name='Communication event type'),
        ),
    ]
