---
  - name: Check if /tmp/.neocli exists
    stat:
      path: /tmp/.neocli
    register: tmp_neocli

  - name: Check if neocli_repo_path exists
    stat:
      path: '{{ neocli_repo_path }}'
    register: neocli_repo_register

  - name: move /tmp/.neocli if it exists
    command: 'cp -R /tmp/.neocli {{ neocli_repo_path }}'
    when: tmp_neocli.stat.exists and not neocli_repo_register.stat.exists

  - name: install neocli
    pip:
      name: '{{ neocli_repo_path }}'
      extra_args: '-e'
    become: yes
    become_user: root

  - name: Overwrite neocli if required
    file:
      state: absent
      path: "{{ neocli_path }}"
    when: overwrite

  - name: Check whether neocli exists
    stat:
      path: "{{ neocli_path }}"
    register: neocli_stat

  - name: Fix permissions
    become_user: root
    command: chown {{ neo_user }} -R {{ user_directory }}

  - name:  python3 neocli init for develop
    command: neocli init {{ neocli_path }} --neo-path {{ neo_repo_url }} --neo-branch {{ neo_branch }} --python {{ python }}
    args:
      creates: "{{ neocli_path }}"
    when: not neocli_stat.stat.exists and not production

  - name: python3 neocli init for production
    command: neocli init {{ neocli_path }} --neo-path {{ neo_repo_url }} --neo-branch {{ neo_branch }} --python {{ python }}
    args:
      creates: "{{ neocli_path }}"
    when: not neocli_stat.stat.exists and production

  # setup common_site_config
  - name: setup config
    command: neocli setup config
    args:
      creates: "{{ neocli_path }}/sites/common_site_config.json"
      chdir: "{{ neocli_path }}"

  - include_tasks: setup_inputrc.yml

  # Setup Procfile
  - name: Setup Procfile
    command: neocli setup procfile
    args:
      creates: "{{ neocli_path }}/Procfile"
      chdir: "{{ neocli_path }}"

  # Setup Redis env for RQ
  - name: Setup Redis
    command: neocli setup redis
    args:
      creates: "{{ neocli_path }}/config/redis_socketio.conf"
      chdir: "{{ neocli_path }}"

  # Setup an ERP Neo site
  - include_tasks: setup_erpneo.yml
    when: not run_travis

  # Setup NeoCLI for production environment
  - include_tasks: setup_neocli_production.yml
    vars:
      neocli_path: "{{ user_directory }}/{{ neocli_name }}"
    when: not run_travis and production
...
