
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T11:46:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c72bdc93c20448e550d913ee778bca7d99e62cd",
 "version": "0.7.1.post.dev453"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
